syntax = "proto3";

package protoapi;
option go_package = "github.com/hezof/protoapi";

import "google/protobuf/descriptor.proto";

message Error {
  uint32 status = 1;               // 错误状态
  uint32 code = 2;                 // 错误代码
  string name = 3;                 // 错误名称
  string message = 4;              // 错误描述
}

message Tag {
  string name = 1;                 // The name of the tag
  string desc = 2;                 // A short description for the tag
}

message Http {

  enum Body {
    json = 0;                      // 解析body使用application/json
    form = 1;                      // 解析body使用multipart/form-data或application/x-www-form-urlencoded
    omit = 2;                      // 忽略解析body
  }

  enum Result {
    simple = 0;                    // 结果使用Result包裹
    unwrap = 1;                    // 结果不用Result包裹
    events = 2;                    // 结果使用Server-Send-Events包裹
  }

  string name = 1;                 // 概要信息
  string desc = 2;                 // 描述信息
  string get = 3;                  // GET请求
  string put = 4;                  // PUT请求
  string post = 5;                 // POST请求
  string delete = 6;               // DELETE请求
  string options = 7;              // OPTIONS请求
  string head = 8;                 // HEAD请求
  string patch = 9;                // PATCH请求
  string trace = 10;               // TRACE请求
  string connect = 11;             // CONNECT请求
  string websocket = 12;           // WS请求(可能与GET冲突)
  Body body = 13;                  // body解析方式. 默认json!
  uint32 status = 14;              // 成功响应状态码
  Result result = 15;              // 结果处理方式.
  repeated Error errors = 16;      // 错误列表
  repeated string tags = 17;       // 标签列表
}

message Role {
  uint64 code = 1;                 // 角色标识
  string name = 2;                 // 角色名称
  string desc = 3;                 // 角色描述
}

message Plugin {
  string val = 1;                  // 插件引用
  Error err = 2;                   // 插件错误
}

message MinLength {
  int64 val = 1;                  // 字串值
  Error err = 2;                  // 错误定义
}

message MaxLength {
  int64 val = 1;                  // 字串值
  Error err = 2;                  // 错误定义
}

message MinItems {
  int64 val = 1;                  // 字串值
  Error err = 2;                  // 错误定义
}

message MaxItems {
  int64 val = 1;                  // 字串值
  Error err = 2;                  // 错误定义
}

message Minimum {
  int64 val = 1;                  // 字串值
  Error err = 2;                  // 错误定义
  bool exclusive = 3;             // 排除边界
}

message Maximum {
  int64 val = 1;                  // 字串值
  Error err = 2;                  // 错误定义
  bool exclusive = 3;             // 排除边界
}

message Enum {
  repeated string str = 1;        // 字串枚举值
  repeated int64 int = 2;         // 整数枚举值
  Error err = 3;                  // 错误定义
}

message Pattern {
  string val = 1;                 // 正则值
  Error err = 2;                  // 错误定义
}

// 对于in为body/form, path, query, header, cookie的参数, 按照OAS 3.0规范解析:
// body/form: style=form, explode=?{false|true}
// path: style=simple, explode=?{false|true}
// query: style=form, explode=?{false|true}
// header: style=simple, explode=?{false|true}
// cookie: style=form, explode=?{false|true}
// 详细内容参考: https://swagger.io/docs/specification/v3_0/serialization
message Prop {

  enum In {
    body = 0;                      // 位于body
    path = 1;                      // 位于path. 对应style=simple及explode=true. 例如: array(blue,black,brown), object(R=100,G=200,B=150)
    query = 2;                     // 位于query. 对应style=form及explode=true. 例如: array(color=blue&color=black&color=brown), object(R=100&G=200&B=150)
    header = 3;                    // 位于header. 对应style=simple及explode=true. 例如: array(blue,black,brown), object(R=100,G=200,B=150)
    cookie = 4;                    // 位于cookie. 对应style=form及explode=true. 例如: array(color=blue&color=black&color=brown), object(R=100&G=200&B=150)
  }

  enum Zero {
    omit_empty = 0;                // 忽略空值, 即omitempty
    with_empty = 1;                // 保留空值, 即忽略omitempty
    conv_empty = 2;                // 转换空值: 对于slice/map,会将null转为[]或{}.
  }

  string name = 1;                 // 概要信息
  string desc = 2;                 // 描述信息
  Zero zero = 3;                   // 值处理策略
  bool enum_name = 4;              // 使用枚举名称而非枚举值.
  In in = 5;                       // 数据位置. body(json, form), path, query, header, cookie
  bool explode = 6;                // 解析方式. primitive类型忽略, array/object类型规则.
}

message Rule {
  Error required = 1;              // 是否必需. 必须声明optional!
  Maximum minimum = 2;             // 最小数值
  Maximum maximum = 3;             // 最大数值
  MinLength min_length = 4;        // 最小长度
  MaxLength max_length = 5;        // 最大长度
  MinItems min_items = 6;          // 最小数量
  MaxItems max_items = 7;          // 最大数量
  Enum enum = 8;                   // 枚举列表
  Pattern pattern = 9;             // 正则匹配
  Plugin plugin = 10;              // 插件校验
}

message Meta {
  string Package = 1;              // 元数据package
  string Service = 2;              // 元数据service
  string Method = 3;               // 元数据method
  bool ClientStreaming = 4;        // 元数据client streaming
  bool ServerStreaming = 5;        // 元数据server streaming
  Http Http = 6;                   // 元数据Http
  Role Role = 7;                   // 元数据Role
  Plugin InputPlugin = 8;          // 元数据message plugin
  repeated Rule InputRules = 9;    // 元数据field rules
}

extend  google.protobuf.ServiceOptions {
  Tag tag = 20000;                // 服务标签
  bool http_only = 20001;         // 仅仅http
}

extend google.protobuf.MethodOptions {
  Http http = 30000;              // http绑定
  Role role = 30001;              // 方法角色
}

extend google.protobuf.MessageOptions {
  string desc = 40000;            // 消息描述
  Plugin plugin = 40001;          // 消息插件
}

extend google.protobuf.FieldOptions {
  Prop prop = 50000;              // 字段属性
  Rule rule = 50001;              // 字段规则
}
