syntax = "proto3";

package protoapi;
option go_package = "github.com/hezof/protoapi";

import "google/protobuf/descriptor.proto";

message Error {
  uint32 status = 1;               // 错误状态
  uint32 code = 2;                 // 错误代码
  string name = 3;                 // 错误名称
  string message = 4;              // 错误描述
}

message Tag {
  string name = 1;                  // The name of the tag
  string desc = 2;                  // A short description for the tag
}

message Http {

  enum Body {
    json = 0;                       // 解析body使用application/json
    form = 1;                       // 解析body使用multipart/form-data或application/x-www-form-urlencoded
    omit = 2;                       // 忽略解析body
  }

  enum Result {
    simple = 0;                    // 结果使用Result包裹
    unwrap = 1;                    // 结果不用Result包裹
    events = 2;                    // 结果使用Server-Send-Events包裹
  }

  string name = 1;                  // 概要信息
  string desc = 2;                  // 描述信息
  string get = 3;                   // GET请求
  string put = 4;                   // PUT请求
  string post = 5;                  // POST请求
  string delete = 6;                // DELETE请求
  string options = 7;               // OPTIONS请求
  string head = 8;                  // HEAD请求
  string patch = 9;                // PATCH请求
  string trace = 10;                // TRACE请求
  string connect = 11;              // CONNECT请求
  string websocket = 12;            // WS请求(可能与GET冲突)
  Body body = 13;                   // body解析方式. 默认json!
  uint32 status = 14;               // 成功响应状态码
  Result result = 15;               // 结果处理方式.
  repeated Error errors = 16;       // 错误列表
  repeated string tags = 17;        // 标签列表
}

message Role {
  uint64 code = 1;                  // 角色标识
  string name = 2;                  // 角色名称
  string desc = 3;                  // 角色描述
}

message Plugin {
  string ref = 1;                  // 插件引用
  Error err = 2;                   // 插件错误
}

message Range {
  int64 val = 1;                  // 字串值
  Error err = 2;                  // 错误定义
}

message RangeExclusive {
  int64 val = 1;                  // 字串值
  Error err = 2;                  // 错误定义
  bool exclusive = 3;             // 排除边界
}

message Enum {
  string val = 1;                 // 数组列表(逗号分隔)
  Error err = 2;                  // 错误定义
}

message Pattern {
  string val = 1;                 // 正则值
  Error err = 2;                  // 错误定义
}

message Prop {

  enum In {
    body = 0;                       // 位于body
    path = 1;                       // 位于path
    query = 2;                      // 位于query
    header = 3;                     // 位于header
    cookie = 4;                     // 位于cookie
  }

  enum Style {
    simple = 0;                     // ARRAY(blue,black,brown), OBJECT(R=100,G=200,B=150)
    form = 1;                       // ARRAY(color=blue&color=black&color=brown), OBJECT(R=100&G=200&B=150)
    json = 2;                       // json
  }

  enum Empty {
    omit_empty = 0;                 // 忽略空值, 即omitempty
    with_empty = 1;                 // 携带空值, 即忽略omitempty
    conv_empty = 2;                 // 转换空值: 对于slice/map,会将null转为[]或{}.
  }

  string name = 1;                  // 概要信息
  string desc = 2;                  // 描述信息
  Empty empty = 3;                  // 值处理策略
  bool escape_html = 4;             // 是否转义html特殊字符.
  bool enum_name = 5;               // 是否使用枚举名称.
  In in = 6;                        // 数据位置. 同openapi的in.
  Style style = 7;                  // 数据式样. 同openapi的style. 用于非json array或object!
  string format = 8;                // 数据格式. 仅用于swagger文档提示.
}

message Rule {
  Error required = 1;               // 是否必需. 必须声明optional!
  RangeExclusive minimum = 2;       // 最小数值
  RangeExclusive maximum = 3;       // 最大数值
  Range min_length = 4;             // 最小长度
  Range max_length = 5;             // 最大长度
  Range min_items = 6;              // 最小数量
  Range max_items = 7;              // 最大数量
  Enum enum = 8;                    // 枚举列表
  Pattern pattern = 9;              // 正则匹配
  Plugin plugin = 10;               // 插件校验
}

extend  google.protobuf.ServiceOptions {
  Tag tag = 20000;                 // 服务标签
  bool http_only = 20001;          // 仅仅http
}

extend google.protobuf.MethodOptions {
  Http http = 30000;              // http绑定
  Role role = 30001;              // 方法角色
}

extend google.protobuf.MessageOptions {
  string desc = 40000;           // 消息描述
  Plugin plugin = 40001;         // 消息插件
}

extend google.protobuf.FieldOptions {
  Prop prop = 50000;             // 字段属性
  Rule rule = 50001;             // 字段规则
}

