package main

import (
	"encoding/base64"
	"fmt"
	"time"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateCodeFile 生成实现文件: *_protoapi.pb.go
func generateImplFile(gen *protogen.Plugin, file *protogen.File, meta *FileExt) {

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+`_protoapi.pb.go`, file.GoImportPath)

	// 1. 输出头部
	protocVersion := "(unknown)"
	if v := gen.Request.GetCompilerVersion(); v != nil {
		protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
	}

	g.P("// Code generated by protoc-gen-go-protoapi. DO NOT EDIT!")
	g.P("// versions:")
	g.P("// - protoc-gen-go-protoapi ", VERSION) // 与依赖的protobuf版本相同
	g.P("// - protoc                 ", protocVersion)
	g.P("// source: ", meta.Path)
	g.P("// create: ", time.Now().Format("2006-01-02 15:04:05"))
	g.P()
	g.P("package ", meta.GoPackage)
	g.P()

	// 2. 输出message(local)的JsonCodec及MessageValidator实现
	for _, m := range meta.Messages.Vec {
		if m.Local {
			implementFieldCodec(g, m)
			if shouldMessageValidator(m) {
				implementMessageValidator(g, m)
			}
		}
	}

	// 3. 输出service(所有service都是本地的)的ServiceRegistry实现
	for _, s := range meta.Services {
		implementServiceRegistry(g, meta, s)
	}
}

func IsKind(f *FieldExt, ks ...protoreflect.Kind) bool {
	for _, k := range ks {
		if f.Kind == k {
			return true
		}
	}
	return false
}

func CreateMeta(f *FileExt, s *ServiceExt, m *MethodExt) *Meta {
	meta := new(Meta)
	meta.Package = f.Package
	meta.Service = s.Name
	meta.Method = m.Name
	meta.ClientStream = m.IsStreamingClient
	meta.ServerStream = m.IsStreamingServer
	meta.Http = m.Http
	meta.Role = m.Role
	meta.MessageExtend = m.InputMessage.Extend
	meta.FieldRules = make([]*Meta_Rule, len(m.InputMessage.Fields))
	for i, v := range m.InputMessage.Fields {
		meta.FieldRules[i] = v.Rule
	}
	return meta
}

// EncodeMeta 断言编码. 用于protogen传值
func EncodeMeta(meta *Meta) string {
	bs, err := proto.Marshal(meta)
	if err != nil {
		panic(fmt.Errorf("ecnode meta error: %v", err))
	}
	return base64.StdEncoding.EncodeToString(bs)
}

// DecodeMeta 断言解码. 用于protogen传值
func DecodeMeta(b64 string) *Meta {
	bs, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		panic(fmt.Errorf("decode meta error: %v", err))
	}
	meta := new(Meta)
	err = proto.Unmarshal(bs, meta)
	if err != nil {
		panic(fmt.Errorf("decode meta error: %v", err))
	}
	return meta
}
