package main

import (
	"fmt"
	"google.golang.org/protobuf/compiler/protogen"
	"hash/crc64"
	"strconv"
	"time"
)

const ProtoapiModule = `github.com/hezof/protoapi`

// generateCodeFile 生成实现文件: *_protoapi.pb.go
func generateImplFile(gen *protogen.Plugin, file *protogen.File, meta *FileExt) {

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+`_protoapi.pb.go`, file.GoImportPath)

	protocVersion := "(unknown)"
	if v := gen.Request.GetCompilerVersion(); v != nil {
		protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
	}

	// 1. 输出头部
	g.P("// Code generated by protoc-gen-go-protoapi. DO NOT EDIT!")
	g.P("// versions:")
	g.P("// - protoc-gen-go-protoapi ", version) // 与依赖的protobuf版本相同
	g.P("// - protoc                 ", protocVersion)
	g.P("// source: ", meta.Path)
	g.P("// create: ", time.Now().Format("2006-01-02 15:04:05"))
	g.P()
	g.P("package ", meta.GoPackage)
	g.P()

	// 2. 输出message(local)的JsonCodec及MessageValidator实现
	for _, m := range meta.Messages.Vec {
		if m.FilePath == meta.Path {
			implementJsonCodec(g, m)
			if shouldMessageValidator(m) {
				implementMessageValidator(g, m)
			}
		}
	}

	// 3. 输出service(local)的ServiceRegistry实现
	for _, s := range meta.Services {
		if s.FilePath == meta.Path {
			implementServiceRegistry(g, s)
		}
	}
}

func implementJsonCodec(g *protogen.GeneratedFile, m *MessageExt) {

}

func implementMessageValidator(g *protogen.GeneratedFile, m *MessageExt) {
	g.QualifiedGoIdent(protogen.GoIdent{GoName: "protoapi", GoImportPath: ProtoapiModule})
	g.QualifiedGoIdent(protogen.GoIdent{GoName: "context", GoImportPath: "context"})
	if m.Plugin != nil {
		g.P("var ", messagePluginName(m), " = protoapi.AssertMessageValidatePlugin(`", m.Plugin.Ref, "`")
	}
	for _, f := range m.Fields {
		if f.Rule != nil && f.Rule.Plugin != nil {
			g.P("var ", fieldPluginName(m, f), " = protoapi.AssertFieldValidatePlugin(`", f.Rule.Plugin, "`")
		}
	}
	g.P("func (x *", g.QualifiedGoIdent(m.GoIdent), ") Validate(ctx context.Context) error {")
	if m.Plugin != nil {

	}
	g.P("	return nil")
	g.P("}")
}

func implementServiceRegistry(g *protogen.GeneratedFile, s *ServiceExt) {

}

func shouldMessageValidator(m *MessageExt) bool {
	if m.Plugin != nil {
		return true
	}
	for _, f := range m.Fields {
		if r := f.Rule; r != nil {
			if r.Required != nil {
				return true
			}
			if r.Minimum != nil {
				return true
			}
			if r.Maximum != nil {
				return true
			}
			if r.MinLength != nil {
				return true
			}
			if r.MaxLength != nil {
				return true
			}
			if r.MinItems != nil {
				return true
			}
			if r.MaxItems != nil {
				return true
			}
			if r.Enum != nil {
				return true
			}
			if r.Pattern != nil {
				return true
			}
			if r.Plugin != nil {
				return true
			}
		}
	}
	return false
}

// 命名规则: _<GoName>_<hash>
func messagePluginName(m *MessageExt) string {
	return `_` + m.GoIdent.GoName + `_` + hash(m.FullName)
}

// 命名规则: _<GoName>_<GoName>_<hash>
func fieldPluginName(m *MessageExt, f *FieldExt) string {
	return `_` + m.GoIdent.GoName + `_` + f.GoName + `_` + hash(f.FullName)
}

func hash(s string) string {
	h := crc64.New(crc64.MakeTable(crc64.ECMA))
	h.Write([]byte(s))
	return strconv.FormatUint(h.Sum64(), 36)
}
