package main

import (
	"fmt"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"time"
)

const ProtoapiModule = `github.com/hezof/protoapi`

// generateCodeFile 生成实现文件: *_protoapi.pb.go
func generateImplFile(gen *protogen.Plugin, file *protogen.File, meta *FileExt) {

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+`_protoapi.pb.go`, file.GoImportPath)

	protocVersion := "(unknown)"
	if v := gen.Request.GetCompilerVersion(); v != nil {
		protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
	}

	// 1. 输出头部
	g.P("// Code generated by protoc-gen-go-protoapi. DO NOT EDIT!")
	g.P("// versions:")
	g.P("// - protoc-gen-go-protoapi ", version) // 与依赖的protobuf版本相同
	g.P("// - protoc                 ", protocVersion)
	g.P("// source: ", meta.Path)
	g.P("// create: ", time.Now().Format("2006-01-02 15:04:05"))
	g.P()
	g.P("package ", meta.GoPackage)
	g.P()

	// 2. 输出message(local)的JsonCodec及MessageValidator实现
	for _, m := range meta.Messages.Vec {
		if m.FilePath == meta.Path {
			implementJsonCodec(g, m)
			if shouldMessageValidator(m) {
				implementMessageValidator(g, m)
			}
		}
	}

	// 3. 输出service(local)的ServiceRegistry实现
	for _, s := range meta.Services {
		if s.FilePath == meta.Path {
			implementServiceRegistry(g, s)
		}
	}
}

func implementJsonCodec(g *protogen.GeneratedFile, m *MessageExt) {

}

func implementMessageValidator(g *protogen.GeneratedFile, m *MessageExt) {
	g.QualifiedGoIdent(protogen.GoIdent{GoName: "protoapi", GoImportPath: ProtoapiModule})
	g.QualifiedGoIdent(protogen.GoIdent{GoName: "context", GoImportPath: "context"})
	g.P("func (x *", g.QualifiedGoIdent(m.GoIdent), ") Validate(set *protoapi.MethodSetting, ctx context.Context) error {")
	if m.Plugin != nil {
		g.P("if err:=set.MessagePlugin(set, ctx, req); err != nil {")
		g.P("return err")
		g.P("}")
	}
	for i, f := range m.Fields {
		if r := f.Rule; r != nil {
			if r.Required != nil {
				g.P("if err:=protoapi.ValidateRequired(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.FieldRules[", i, "].Required); err != nil {")
				g.P("return err")
				g.P("}")
			}
			if r.Minimum != nil {
				g.P("if err:=protoapi.ValidateMinimum(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.FieldRules[", i, "].Minimum); err != nil {")
				g.P("return err")
				g.P("}")
			}
			if r.Maximum != nil {
				g.P("if err:=protoapi.ValidateMaximum(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.FieldRules[", i, "].Maximum); err != nil {")
				g.P("return err")
				g.P("}")
			}
			if r.MinLength != nil {
				g.P("if err:=protoapi.ValidateMinLength(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.FieldRules[", i, "].MinLength); err != nil {")
				g.P("return err")
				g.P("}")
			}
			if r.MaxLength != nil {
				g.P("if err:=protoapi.ValidateMaxLength(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.FieldRules[", i, "].MaxLength); err != nil {")
				g.P("return err")
				g.P("}")
			}
			if r.MinItems != nil {
				g.P("if err:=protoapi.ValidateMinItems(ctx, `", f.Name, "`, x.", f.GoName, ",set.Meta.FieldRules[", i, "].MinItems); err != nil {")
				g.P("return err")
				g.P("}")
			}
			if r.MaxItems != nil {
				g.P("if err:=protoapi.ValidateMaxItems(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.FieldRules[", i, "].MaxItems); err != nil {")
				g.P("return err")
				g.P("}")
			}
			if r.Enum != nil {
				if f.Kind == protoreflect.StringKind {
					g.P("if err:=protoapi.ValidateEnumStr(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.FieldRules[", i, "].Enum); err != nil {")
					g.P("return err")
					g.P("}")
				} else {
					g.P("if err:=protoapi.ValidateEnumInt(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.FieldRules[", i, "].Enum); err != nil {")
					g.P("return err")
					g.P("}")
				}
			}
			if r.Pattern != nil {
				g.P("if err:=protoapi.ValidatePattern(ctx, `", f.Name, "`, x.", f.GoName, ", set.Meta.InputRules[", i, "].Pattern, set.Meta.FieldPatterns[", i, "]); err != nil {")
				g.P("return err")
				g.P("}")
			}
			if r.Plugin != nil {
				g.P("if err:=set.FieldPlugins[", i, "](`", f.Name, "`, x.", f.GoName, ", set.Meta.InputRules[", i, "].Plugin); err != nil {")
				g.P("return err")
				g.P("}")
			}
		}
	}
	g.P("return nil")
	g.P("}")
}

func implementServiceRegistry(g *protogen.GeneratedFile, s *ServiceExt) {

}

func shouldMessageValidator(m *MessageExt) bool {
	if m.Plugin != nil {
		return true
	}
	for _, f := range m.Fields {
		if r := f.Rule; r != nil {
			if r.Required != nil {
				return true
			}
			if r.Minimum != nil {
				return true
			}
			if r.Maximum != nil {
				return true
			}
			if r.MinLength != nil {
				return true
			}
			if r.MaxLength != nil {
				return true
			}
			if r.MinItems != nil {
				return true
			}
			if r.MaxItems != nil {
				return true
			}
			if r.Enum != nil {
				return true
			}
			if r.Pattern != nil {
				return true
			}
			if r.Plugin != nil {
				return true
			}
		}
	}
	return false
}
