// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.21.12
// source: protoapi.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Http_Body int32

const (
	Http_json Http_Body = 0 // 解析body使用application/json
	Http_form Http_Body = 1 // 解析body使用multipart/form-data或application/x-www-form-urlencoded
	Http_omit Http_Body = 2 // 忽略解析body
)

// Enum value maps for Http_Body.
var (
	Http_Body_name = map[int32]string{
		0: "json",
		1: "form",
		2: "omit",
	}
	Http_Body_value = map[string]int32{
		"json": 0,
		"form": 1,
		"omit": 2,
	}
)

func (x Http_Body) Enum() *Http_Body {
	p := new(Http_Body)
	*p = x
	return p
}

func (x Http_Body) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Http_Body) Descriptor() protoreflect.EnumDescriptor {
	return file_protoapi_proto_enumTypes[0].Descriptor()
}

func (Http_Body) Type() protoreflect.EnumType {
	return &file_protoapi_proto_enumTypes[0]
}

func (x Http_Body) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Http_Body.Descriptor instead.
func (Http_Body) EnumDescriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{2, 0}
}

type Http_Result int32

const (
	Http_simple Http_Result = 0 // 结果使用Result包裹
	Http_unwrap Http_Result = 1 // 结果不用Result包裹
	Http_events Http_Result = 2 // 结果使用Server-Send-Events包裹
)

// Enum value maps for Http_Result.
var (
	Http_Result_name = map[int32]string{
		0: "simple",
		1: "unwrap",
		2: "events",
	}
	Http_Result_value = map[string]int32{
		"simple": 0,
		"unwrap": 1,
		"events": 2,
	}
)

func (x Http_Result) Enum() *Http_Result {
	p := new(Http_Result)
	*p = x
	return p
}

func (x Http_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Http_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_protoapi_proto_enumTypes[1].Descriptor()
}

func (Http_Result) Type() protoreflect.EnumType {
	return &file_protoapi_proto_enumTypes[1]
}

func (x Http_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Http_Result.Descriptor instead.
func (Http_Result) EnumDescriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{2, 1}
}

type Prop_In int32

const (
	Prop_body   Prop_In = 0 // 位于body
	Prop_path   Prop_In = 1 // 位于path. 对应style=simple及explode=true. 例如: array(blue,black,brown), object(R=100,G=200,B=150)
	Prop_query  Prop_In = 2 // 位于query. 对应style=form及explode=true. 例如: array(color=blue&color=black&color=brown), object(R=100&G=200&B=150)
	Prop_header Prop_In = 3 // 位于header. 对应style=simple及explode=true. 例如: array(blue,black,brown), object(R=100,G=200,B=150)
	Prop_cookie Prop_In = 4 // 位于cookie. 对应style=form及explode=true. 例如: array(color=blue&color=black&color=brown), object(R=100&G=200&B=150)
)

// Enum value maps for Prop_In.
var (
	Prop_In_name = map[int32]string{
		0: "body",
		1: "path",
		2: "query",
		3: "header",
		4: "cookie",
	}
	Prop_In_value = map[string]int32{
		"body":   0,
		"path":   1,
		"query":  2,
		"header": 3,
		"cookie": 4,
	}
)

func (x Prop_In) Enum() *Prop_In {
	p := new(Prop_In)
	*p = x
	return p
}

func (x Prop_In) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Prop_In) Descriptor() protoreflect.EnumDescriptor {
	return file_protoapi_proto_enumTypes[2].Descriptor()
}

func (Prop_In) Type() protoreflect.EnumType {
	return &file_protoapi_proto_enumTypes[2]
}

func (x Prop_In) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Prop_In.Descriptor instead.
func (Prop_In) EnumDescriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{13, 0}
}

type Prop_Zero int32

const (
	Prop_omit_empty Prop_Zero = 0 // 忽略空值, 即omitempty
	Prop_with_empty Prop_Zero = 1 // 保留空值, 即忽略omitempty
	Prop_conv_empty Prop_Zero = 2 // 转换空值: 对于slice/map,会将null转为[]或{}.
)

// Enum value maps for Prop_Zero.
var (
	Prop_Zero_name = map[int32]string{
		0: "omit_empty",
		1: "with_empty",
		2: "conv_empty",
	}
	Prop_Zero_value = map[string]int32{
		"omit_empty": 0,
		"with_empty": 1,
		"conv_empty": 2,
	}
)

func (x Prop_Zero) Enum() *Prop_Zero {
	p := new(Prop_Zero)
	*p = x
	return p
}

func (x Prop_Zero) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Prop_Zero) Descriptor() protoreflect.EnumDescriptor {
	return file_protoapi_proto_enumTypes[3].Descriptor()
}

func (Prop_Zero) Type() protoreflect.EnumType {
	return &file_protoapi_proto_enumTypes[3]
}

func (x Prop_Zero) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Prop_Zero.Descriptor instead.
func (Prop_Zero) EnumDescriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{13, 1}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`  // 错误状态
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 错误代码
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`       // 错误名称
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // 错误消息
	Details       []string               `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"` // 错误参数(用于国际化)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protoapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // The name of the tag
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"` // A short description for the tag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_protoapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Http struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                 // 概要信息
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`                                 // 描述信息
	Get           string                 `protobuf:"bytes,3,opt,name=get,proto3" json:"get,omitempty"`                                   // GET请求
	Put           string                 `protobuf:"bytes,4,opt,name=put,proto3" json:"put,omitempty"`                                   // PUT请求
	Post          string                 `protobuf:"bytes,5,opt,name=post,proto3" json:"post,omitempty"`                                 // POST请求
	Delete        string                 `protobuf:"bytes,6,opt,name=delete,proto3" json:"delete,omitempty"`                             // DELETE请求
	Options       string                 `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`                           // OPTIONS请求
	Head          string                 `protobuf:"bytes,8,opt,name=head,proto3" json:"head,omitempty"`                                 // HEAD请求
	Patch         string                 `protobuf:"bytes,9,opt,name=patch,proto3" json:"patch,omitempty"`                               // PATCH请求
	Trace         string                 `protobuf:"bytes,10,opt,name=trace,proto3" json:"trace,omitempty"`                              // TRACE请求
	Connect       string                 `protobuf:"bytes,11,opt,name=connect,proto3" json:"connect,omitempty"`                          // CONNECT请求
	Websocket     string                 `protobuf:"bytes,12,opt,name=websocket,proto3" json:"websocket,omitempty"`                      // WS请求(可能与GET冲突)
	Body          Http_Body              `protobuf:"varint,13,opt,name=body,proto3,enum=protoapi.Http_Body" json:"body,omitempty"`       // body解析方式. 默认json!
	Status        uint32                 `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`                           // 成功响应状态码
	Result        Http_Result            `protobuf:"varint,15,opt,name=result,proto3,enum=protoapi.Http_Result" json:"result,omitempty"` // 结果处理方式.
	Errors        []*Error               `protobuf:"bytes,16,rep,name=errors,proto3" json:"errors,omitempty"`                            // 错误列表
	Tags          []string               `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`                                // 标签列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Http) Reset() {
	*x = Http{}
	mi := &file_protoapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http) ProtoMessage() {}

func (x *Http) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http.ProtoReflect.Descriptor instead.
func (*Http) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{2}
}

func (x *Http) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Http) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Http) GetGet() string {
	if x != nil {
		return x.Get
	}
	return ""
}

func (x *Http) GetPut() string {
	if x != nil {
		return x.Put
	}
	return ""
}

func (x *Http) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *Http) GetDelete() string {
	if x != nil {
		return x.Delete
	}
	return ""
}

func (x *Http) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *Http) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *Http) GetPatch() string {
	if x != nil {
		return x.Patch
	}
	return ""
}

func (x *Http) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

func (x *Http) GetConnect() string {
	if x != nil {
		return x.Connect
	}
	return ""
}

func (x *Http) GetWebsocket() string {
	if x != nil {
		return x.Websocket
	}
	return ""
}

func (x *Http) GetBody() Http_Body {
	if x != nil {
		return x.Body
	}
	return Http_json
}

func (x *Http) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Http) GetResult() Http_Result {
	if x != nil {
		return x.Result
	}
	return Http_simple
}

func (x *Http) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Http) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 角色标识
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // 角色名称
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`  // 角色描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_protoapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{3}
}

func (x *Role) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Plugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"` // 插件引用
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` // 插件错误
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_protoapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{4}
}

func (x *Plugin) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *Plugin) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type MinLength struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"` // 字串值
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`  // 错误定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinLength) Reset() {
	*x = MinLength{}
	mi := &file_protoapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinLength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinLength) ProtoMessage() {}

func (x *MinLength) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinLength.ProtoReflect.Descriptor instead.
func (*MinLength) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{5}
}

func (x *MinLength) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *MinLength) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type MaxLength struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"` // 字串值
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`  // 错误定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxLength) Reset() {
	*x = MaxLength{}
	mi := &file_protoapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxLength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxLength) ProtoMessage() {}

func (x *MaxLength) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxLength.ProtoReflect.Descriptor instead.
func (*MaxLength) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{6}
}

func (x *MaxLength) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *MaxLength) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type MinItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"` // 字串值
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`  // 错误定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinItems) Reset() {
	*x = MinItems{}
	mi := &file_protoapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinItems) ProtoMessage() {}

func (x *MinItems) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinItems.ProtoReflect.Descriptor instead.
func (*MinItems) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{7}
}

func (x *MinItems) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *MinItems) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type MaxItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"` // 字串值
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`  // 错误定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxItems) Reset() {
	*x = MaxItems{}
	mi := &file_protoapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxItems) ProtoMessage() {}

func (x *MaxItems) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxItems.ProtoReflect.Descriptor instead.
func (*MaxItems) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{8}
}

func (x *MaxItems) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *MaxItems) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type Minimum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`             // 字串值
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`              // 错误定义
	Exclusive     bool                   `protobuf:"varint,3,opt,name=exclusive,proto3" json:"exclusive,omitempty"` // 排除边界
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Minimum) Reset() {
	*x = Minimum{}
	mi := &file_protoapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Minimum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Minimum) ProtoMessage() {}

func (x *Minimum) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Minimum.ProtoReflect.Descriptor instead.
func (*Minimum) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{9}
}

func (x *Minimum) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *Minimum) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *Minimum) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type Maximum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`             // 字串值
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`              // 错误定义
	Exclusive     bool                   `protobuf:"varint,3,opt,name=exclusive,proto3" json:"exclusive,omitempty"` // 排除边界
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maximum) Reset() {
	*x = Maximum{}
	mi := &file_protoapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maximum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maximum) ProtoMessage() {}

func (x *Maximum) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maximum.ProtoReflect.Descriptor instead.
func (*Maximum) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{10}
}

func (x *Maximum) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *Maximum) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *Maximum) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           []string               `protobuf:"bytes,1,rep,name=str,proto3" json:"str,omitempty"`         // 字串枚举值
	Int           []int64                `protobuf:"varint,2,rep,packed,name=int,proto3" json:"int,omitempty"` // 整数枚举值
	Err           *Error                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`         // 错误定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_protoapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{11}
}

func (x *Enum) GetStr() []string {
	if x != nil {
		return x.Str
	}
	return nil
}

func (x *Enum) GetInt() []int64 {
	if x != nil {
		return x.Int
	}
	return nil
}

func (x *Enum) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type Pattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"` // 正则值
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` // 错误定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pattern) Reset() {
	*x = Pattern{}
	mi := &file_protoapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pattern) ProtoMessage() {}

func (x *Pattern) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pattern.ProtoReflect.Descriptor instead.
func (*Pattern) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{12}
}

func (x *Pattern) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *Pattern) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

// 对于in为body/form, path, query, header, cookie的参数, 按照OAS 3.0规范解析:
// body/form: style=form, explode=?{false|true}
// path: style=simple, explode=?{false|true}
// query: style=form, explode=?{false|true}
// header: style=simple, explode=?{false|true}
// cookie: style=form, explode=?{false|true}
// 详细内容参考: https://swagger.io/docs/specification/v3_0/serialization
type Prop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                          // 概要信息
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`                          // 描述信息
	Zero          Prop_Zero              `protobuf:"varint,3,opt,name=zero,proto3,enum=protoapi.Prop_Zero" json:"zero,omitempty"` // 值处理策略
	EnumName      bool                   `protobuf:"varint,4,opt,name=enum_name,json=enumName,proto3" json:"enum_name,omitempty"` // 使用枚举名称而非枚举值.
	In            Prop_In                `protobuf:"varint,5,opt,name=in,proto3,enum=protoapi.Prop_In" json:"in,omitempty"`       // 数据位置. body(json, form), path, query, header, cookie
	Explode       bool                   `protobuf:"varint,6,opt,name=explode,proto3" json:"explode,omitempty"`                   // 解析方式. primitive类型忽略, array/object类型规则.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prop) Reset() {
	*x = Prop{}
	mi := &file_protoapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prop) ProtoMessage() {}

func (x *Prop) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prop.ProtoReflect.Descriptor instead.
func (*Prop) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{13}
}

func (x *Prop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prop) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Prop) GetZero() Prop_Zero {
	if x != nil {
		return x.Zero
	}
	return Prop_omit_empty
}

func (x *Prop) GetEnumName() bool {
	if x != nil {
		return x.EnumName
	}
	return false
}

func (x *Prop) GetIn() Prop_In {
	if x != nil {
		return x.In
	}
	return Prop_body
}

func (x *Prop) GetExplode() bool {
	if x != nil {
		return x.Explode
	}
	return false
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Required      *Error                 `protobuf:"bytes,1,opt,name=required,proto3" json:"required,omitempty"`                    // 是否必需. 必须声明optional!
	Minimum       *Maximum               `protobuf:"bytes,2,opt,name=minimum,proto3" json:"minimum,omitempty"`                      // 最小数值
	Maximum       *Maximum               `protobuf:"bytes,3,opt,name=maximum,proto3" json:"maximum,omitempty"`                      // 最大数值
	MinLength     *MinLength             `protobuf:"bytes,4,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"` // 最小长度
	MaxLength     *MaxLength             `protobuf:"bytes,5,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"` // 最大长度
	MinItems      *MinItems              `protobuf:"bytes,6,opt,name=min_items,json=minItems,proto3" json:"min_items,omitempty"`    // 最小数量
	MaxItems      *MaxItems              `protobuf:"bytes,7,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`    // 最大数量
	Enum          *Enum                  `protobuf:"bytes,8,opt,name=enum,proto3" json:"enum,omitempty"`                            // 枚举列表
	Pattern       *Pattern               `protobuf:"bytes,9,opt,name=pattern,proto3" json:"pattern,omitempty"`                      // 正则匹配
	Plugin        *Plugin                `protobuf:"bytes,10,opt,name=plugin,proto3" json:"plugin,omitempty"`                       // 插件校验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_protoapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{14}
}

func (x *Rule) GetRequired() *Error {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *Rule) GetMinimum() *Maximum {
	if x != nil {
		return x.Minimum
	}
	return nil
}

func (x *Rule) GetMaximum() *Maximum {
	if x != nil {
		return x.Maximum
	}
	return nil
}

func (x *Rule) GetMinLength() *MinLength {
	if x != nil {
		return x.MinLength
	}
	return nil
}

func (x *Rule) GetMaxLength() *MaxLength {
	if x != nil {
		return x.MaxLength
	}
	return nil
}

func (x *Rule) GetMinItems() *MinItems {
	if x != nil {
		return x.MinItems
	}
	return nil
}

func (x *Rule) GetMaxItems() *MaxItems {
	if x != nil {
		return x.MaxItems
	}
	return nil
}

func (x *Rule) GetEnum() *Enum {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Rule) GetPattern() *Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *Rule) GetPlugin() *Plugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

type Meta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Package         string                 `protobuf:"bytes,1,opt,name=Package,proto3" json:"Package,omitempty"`                  // 元数据package
	Service         string                 `protobuf:"bytes,2,opt,name=Service,proto3" json:"Service,omitempty"`                  // 元数据service
	Method          string                 `protobuf:"bytes,3,opt,name=Method,proto3" json:"Method,omitempty"`                    // 元数据method
	ClientStreaming bool                   `protobuf:"varint,4,opt,name=ClientStreaming,proto3" json:"ClientStreaming,omitempty"` // 元数据client streaming
	ServerStreaming bool                   `protobuf:"varint,5,opt,name=ServerStreaming,proto3" json:"ServerStreaming,omitempty"` // 元数据server streaming
	Http            *Http                  `protobuf:"bytes,6,opt,name=Http,proto3" json:"Http,omitempty"`                        // 元数据Http
	Role            *Role                  `protobuf:"bytes,7,opt,name=Role,proto3" json:"Role,omitempty"`                        // 元数据Role
	MessagePlugin   *Plugin                `protobuf:"bytes,8,opt,name=MessagePlugin,proto3" json:"MessagePlugin,omitempty"`      // 元数据message plugin
	FieldRules      []*Rule                `protobuf:"bytes,9,rep,name=FieldRules,proto3" json:"FieldRules,omitempty"`            // 元数据field rules
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_protoapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{15}
}

func (x *Meta) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Meta) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Meta) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Meta) GetClientStreaming() bool {
	if x != nil {
		return x.ClientStreaming
	}
	return false
}

func (x *Meta) GetServerStreaming() bool {
	if x != nil {
		return x.ServerStreaming
	}
	return false
}

func (x *Meta) GetHttp() *Http {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Meta) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *Meta) GetMessagePlugin() *Plugin {
	if x != nil {
		return x.MessagePlugin
	}
	return nil
}

func (x *Meta) GetFieldRules() []*Rule {
	if x != nil {
		return x.FieldRules
	}
	return nil
}

var file_protoapi_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Tag)(nil),
		Field:         20000,
		Name:          "protoapi.tag",
		Tag:           "bytes,20000,opt,name=tag",
		Filename:      "protoapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         20001,
		Name:          "protoapi.http_only",
		Tag:           "varint,20001,opt,name=http_only",
		Filename:      "protoapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Http)(nil),
		Field:         30000,
		Name:          "protoapi.http",
		Tag:           "bytes,30000,opt,name=http",
		Filename:      "protoapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Role)(nil),
		Field:         30001,
		Name:          "protoapi.role",
		Tag:           "bytes,30001,opt,name=role",
		Filename:      "protoapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         40000,
		Name:          "protoapi.desc",
		Tag:           "bytes,40000,opt,name=desc",
		Filename:      "protoapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Plugin)(nil),
		Field:         40001,
		Name:          "protoapi.plugin",
		Tag:           "bytes,40001,opt,name=plugin",
		Filename:      "protoapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Prop)(nil),
		Field:         50000,
		Name:          "protoapi.prop",
		Tag:           "bytes,50000,opt,name=prop",
		Filename:      "protoapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Rule)(nil),
		Field:         50001,
		Name:          "protoapi.rule",
		Tag:           "bytes,50001,opt,name=rule",
		Filename:      "protoapi.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional protoapi.Tag tag = 20000;
	E_Tag = &file_protoapi_proto_extTypes[0] // 服务标签
	// optional bool http_only = 20001;
	E_HttpOnly = &file_protoapi_proto_extTypes[1] // 仅仅http
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional protoapi.Http http = 30000;
	E_Http = &file_protoapi_proto_extTypes[2] // http绑定
	// optional protoapi.Role role = 30001;
	E_Role = &file_protoapi_proto_extTypes[3] // 方法角色
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string desc = 40000;
	E_Desc = &file_protoapi_proto_extTypes[4] // 消息描述
	// optional protoapi.Plugin plugin = 40001;
	E_Plugin = &file_protoapi_proto_extTypes[5] // 消息插件
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional protoapi.Prop prop = 50000;
	E_Prop = &file_protoapi_proto_extTypes[6] // 字段属性
	// optional protoapi.Rule rule = 50001;
	E_Rule = &file_protoapi_proto_extTypes[7] // 字段规则
)

var File_protoapi_proto protoreflect.FileDescriptor

var file_protoapi_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x2d, 0x0a, 0x03, 0x54, 0x61, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x91, 0x04, 0x0a, 0x04, 0x48, 0x74, 0x74,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x11, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x24, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x08, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x66, 0x6f,
	0x72, 0x6d, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x6f, 0x6d, 0x69, 0x74, 0x10, 0x02, 0x22, 0x2c,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x75, 0x6e, 0x77, 0x72, 0x61, 0x70, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x10, 0x02, 0x22, 0x42, 0x0a, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x22, 0x3d, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x21, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22,
	0x40, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x21,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x22, 0x40, 0x0a, 0x09, 0x4d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x22, 0x3f, 0x0a, 0x08, 0x4d, 0x69, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61,
	0x6c, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x22, 0x3f, 0x0a, 0x08, 0x4d, 0x61, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x5c, 0x0a, 0x07, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69,
	0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73,
	0x69, 0x76, 0x65, 0x22, 0x5c, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76,
	0x65, 0x22, 0x4d, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x21, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72,
	0x22, 0x3e, 0x0a, 0x07, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x21, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72,
	0x22, 0xa6, 0x02, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x12, 0x27, 0x0a, 0x04, 0x7a, 0x65, 0x72, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x2e,
	0x5a, 0x65, 0x72, 0x6f, 0x52, 0x04, 0x7a, 0x65, 0x72, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e,
	0x75, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65,
	0x6e, 0x75, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x2e, 0x49, 0x6e, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78,
	0x70, 0x6c, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x78, 0x70,
	0x6c, 0x6f, 0x64, 0x65, 0x22, 0x3b, 0x0a, 0x02, 0x49, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x10,
	0x04, 0x22, 0x36, 0x0a, 0x04, 0x5a, 0x65, 0x72, 0x6f, 0x12, 0x0e, 0x0a, 0x0a, 0x6f, 0x6d, 0x69,
	0x74, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x76, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x02, 0x22, 0xd2, 0x03, 0x0a, 0x04, 0x52, 0x75,
	0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12,
	0x2b, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x78, 0x69,
	0x6d, 0x75, 0x6d, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x2b, 0x0a, 0x07,
	0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d,
	0x52, 0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x32, 0x0a, 0x0a, 0x6d, 0x69, 0x6e,
	0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x32, 0x0a,
	0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x78,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x2f, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x69, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69,
	0x2e, 0x4d, 0x61, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x52, 0x07, 0x70, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x6e, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22, 0xd6,
	0x02, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x0a,
	0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x04, 0x48, 0x74, 0x74, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69,
	0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x04, 0x48, 0x74, 0x74, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x52,
	0x6f, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x36, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x2e, 0x0a, 0x0a, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0a, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x3a, 0x42, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1f,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xa0, 0x9c, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x03, 0x74, 0x61, 0x67, 0x3a, 0x3e, 0x0a, 0x09, 0x68,
	0x74, 0x74, 0x70, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa1, 0x9c, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x4f, 0x6e, 0x6c, 0x79, 0x3a, 0x44, 0x0a, 0x04, 0x68,
	0x74, 0x74, 0x70, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xb0, 0xea, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x04, 0x68, 0x74, 0x74,
	0x70, 0x3a, 0x44, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb1, 0xea, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x3a, 0x35, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xc0, 0xb8, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x3a, 0x4b,
	0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xc1, 0xb8, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x3a, 0x43, 0x0a, 0x04, 0x70,
	0x72, 0x6f, 0x70, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x04, 0x70, 0x72, 0x6f, 0x70,
	0x3a, 0x43, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52,
	0x04, 0x72, 0x75, 0x6c, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x7a, 0x6f, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoapi_proto_rawDescOnce sync.Once
	file_protoapi_proto_rawDescData = file_protoapi_proto_rawDesc
)

func file_protoapi_proto_rawDescGZIP() []byte {
	file_protoapi_proto_rawDescOnce.Do(func() {
		file_protoapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoapi_proto_rawDescData)
	})
	return file_protoapi_proto_rawDescData
}

var file_protoapi_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_protoapi_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protoapi_proto_goTypes = []any{
	(Http_Body)(0),                      // 0: protoapi.Http.Body
	(Http_Result)(0),                    // 1: protoapi.Http.Result
	(Prop_In)(0),                        // 2: protoapi.Prop.In
	(Prop_Zero)(0),                      // 3: protoapi.Prop.Zero
	(*Error)(nil),                       // 4: protoapi.Error
	(*Tag)(nil),                         // 5: protoapi.Tag
	(*Http)(nil),                        // 6: protoapi.Http
	(*Role)(nil),                        // 7: protoapi.Role
	(*Plugin)(nil),                      // 8: protoapi.Plugin
	(*MinLength)(nil),                   // 9: protoapi.MinLength
	(*MaxLength)(nil),                   // 10: protoapi.MaxLength
	(*MinItems)(nil),                    // 11: protoapi.MinItems
	(*MaxItems)(nil),                    // 12: protoapi.MaxItems
	(*Minimum)(nil),                     // 13: protoapi.Minimum
	(*Maximum)(nil),                     // 14: protoapi.Maximum
	(*Enum)(nil),                        // 15: protoapi.Enum
	(*Pattern)(nil),                     // 16: protoapi.Pattern
	(*Prop)(nil),                        // 17: protoapi.Prop
	(*Rule)(nil),                        // 18: protoapi.Rule
	(*Meta)(nil),                        // 19: protoapi.Meta
	(*descriptorpb.ServiceOptions)(nil), // 20: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 21: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 22: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 23: google.protobuf.FieldOptions
}
var file_protoapi_proto_depIdxs = []int32{
	0,  // 0: protoapi.Http.body:type_name -> protoapi.Http.Body
	1,  // 1: protoapi.Http.result:type_name -> protoapi.Http.Result
	4,  // 2: protoapi.Http.errors:type_name -> protoapi.Error
	4,  // 3: protoapi.Plugin.err:type_name -> protoapi.Error
	4,  // 4: protoapi.MinLength.err:type_name -> protoapi.Error
	4,  // 5: protoapi.MaxLength.err:type_name -> protoapi.Error
	4,  // 6: protoapi.MinItems.err:type_name -> protoapi.Error
	4,  // 7: protoapi.MaxItems.err:type_name -> protoapi.Error
	4,  // 8: protoapi.Minimum.err:type_name -> protoapi.Error
	4,  // 9: protoapi.Maximum.err:type_name -> protoapi.Error
	4,  // 10: protoapi.Enum.err:type_name -> protoapi.Error
	4,  // 11: protoapi.Pattern.err:type_name -> protoapi.Error
	3,  // 12: protoapi.Prop.zero:type_name -> protoapi.Prop.Zero
	2,  // 13: protoapi.Prop.in:type_name -> protoapi.Prop.In
	4,  // 14: protoapi.Rule.required:type_name -> protoapi.Error
	14, // 15: protoapi.Rule.minimum:type_name -> protoapi.Maximum
	14, // 16: protoapi.Rule.maximum:type_name -> protoapi.Maximum
	9,  // 17: protoapi.Rule.min_length:type_name -> protoapi.MinLength
	10, // 18: protoapi.Rule.max_length:type_name -> protoapi.MaxLength
	11, // 19: protoapi.Rule.min_items:type_name -> protoapi.MinItems
	12, // 20: protoapi.Rule.max_items:type_name -> protoapi.MaxItems
	15, // 21: protoapi.Rule.enum:type_name -> protoapi.Enum
	16, // 22: protoapi.Rule.pattern:type_name -> protoapi.Pattern
	8,  // 23: protoapi.Rule.plugin:type_name -> protoapi.Plugin
	6,  // 24: protoapi.Meta.Http:type_name -> protoapi.Http
	7,  // 25: protoapi.Meta.Role:type_name -> protoapi.Role
	8,  // 26: protoapi.Meta.MessagePlugin:type_name -> protoapi.Plugin
	18, // 27: protoapi.Meta.FieldRules:type_name -> protoapi.Rule
	20, // 28: protoapi.tag:extendee -> google.protobuf.ServiceOptions
	20, // 29: protoapi.http_only:extendee -> google.protobuf.ServiceOptions
	21, // 30: protoapi.http:extendee -> google.protobuf.MethodOptions
	21, // 31: protoapi.role:extendee -> google.protobuf.MethodOptions
	22, // 32: protoapi.desc:extendee -> google.protobuf.MessageOptions
	22, // 33: protoapi.plugin:extendee -> google.protobuf.MessageOptions
	23, // 34: protoapi.prop:extendee -> google.protobuf.FieldOptions
	23, // 35: protoapi.rule:extendee -> google.protobuf.FieldOptions
	5,  // 36: protoapi.tag:type_name -> protoapi.Tag
	6,  // 37: protoapi.http:type_name -> protoapi.Http
	7,  // 38: protoapi.role:type_name -> protoapi.Role
	8,  // 39: protoapi.plugin:type_name -> protoapi.Plugin
	17, // 40: protoapi.prop:type_name -> protoapi.Prop
	18, // 41: protoapi.rule:type_name -> protoapi.Rule
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	36, // [36:42] is the sub-list for extension type_name
	28, // [28:36] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_protoapi_proto_init() }
func file_protoapi_proto_init() {
	if File_protoapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoapi_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 8,
			NumServices:   0,
		},
		GoTypes:           file_protoapi_proto_goTypes,
		DependencyIndexes: file_protoapi_proto_depIdxs,
		EnumInfos:         file_protoapi_proto_enumTypes,
		MessageInfos:      file_protoapi_proto_msgTypes,
		ExtensionInfos:    file_protoapi_proto_extTypes,
	}.Build()
	File_protoapi_proto = out.File
	file_protoapi_proto_rawDesc = nil
	file_protoapi_proto_goTypes = nil
	file_protoapi_proto_depIdxs = nil
}
