// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: demo.proto

package test

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Demo_Simple_FullMethodName        = "/test.Demo/Simple"
	Demo_Client_FullMethodName        = "/test.Demo/Client"
	Demo_Server_FullMethodName        = "/test.Demo/Server"
	Demo_Bidirectional_FullMethodName = "/test.Demo/Bidirectional"
)

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoClient interface {
	Simple(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Rsp, error)
	Client(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Req, Rsp], error)
	Server(ctx context.Context, in *Req, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Rsp], error)
	Bidirectional(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Req, Rsp], error)
}

type demoClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoClient(cc grpc.ClientConnInterface) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) Simple(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Rsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rsp)
	err := c.cc.Invoke(ctx, Demo_Simple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) Client(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Req, Rsp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Demo_ServiceDesc.Streams[0], Demo_Client_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Req, Rsp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Demo_ClientClient = grpc.ClientStreamingClient[Req, Rsp]

func (c *demoClient) Server(ctx context.Context, in *Req, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Rsp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Demo_ServiceDesc.Streams[1], Demo_Server_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Req, Rsp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Demo_ServerClient = grpc.ServerStreamingClient[Rsp]

func (c *demoClient) Bidirectional(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Req, Rsp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Demo_ServiceDesc.Streams[2], Demo_Bidirectional_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Req, Rsp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Demo_BidirectionalClient = grpc.BidiStreamingClient[Req, Rsp]

// DemoServer is the server API for Demo service.
// All implementations should embed UnimplementedDemoServer
// for forward compatibility.
type DemoServer interface {
	Simple(context.Context, *Req) (*Rsp, error)
	Client(grpc.ClientStreamingServer[Req, Rsp]) error
	Server(*Req, grpc.ServerStreamingServer[Rsp]) error
	Bidirectional(grpc.BidiStreamingServer[Req, Rsp]) error
}

// UnimplementedDemoServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemoServer struct{}

func (UnimplementedDemoServer) Simple(context.Context, *Req) (*Rsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simple not implemented")
}
func (UnimplementedDemoServer) Client(grpc.ClientStreamingServer[Req, Rsp]) error {
	return status.Errorf(codes.Unimplemented, "method Client not implemented")
}
func (UnimplementedDemoServer) Server(*Req, grpc.ServerStreamingServer[Rsp]) error {
	return status.Errorf(codes.Unimplemented, "method Server not implemented")
}
func (UnimplementedDemoServer) Bidirectional(grpc.BidiStreamingServer[Req, Rsp]) error {
	return status.Errorf(codes.Unimplemented, "method Bidirectional not implemented")
}
func (UnimplementedDemoServer) testEmbeddedByValue() {}

// UnsafeDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoServer will
// result in compilation errors.
type UnsafeDemoServer interface {
	mustEmbedUnimplementedDemoServer()
}

func RegisterDemoServer(s grpc.ServiceRegistrar, srv DemoServer) {
	// If the following call pancis, it indicates UnimplementedDemoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Demo_ServiceDesc, srv)
}

func _Demo_Simple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demo_Simple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).Simple(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_Client_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServer).Client(&grpc.GenericServerStream[Req, Rsp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Demo_ClientServer = grpc.ClientStreamingServer[Req, Rsp]

func _Demo_Server_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Req)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DemoServer).Server(m, &grpc.GenericServerStream[Req, Rsp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Demo_ServerServer = grpc.ServerStreamingServer[Rsp]

func _Demo_Bidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServer).Bidirectional(&grpc.GenericServerStream[Req, Rsp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Demo_BidirectionalServer = grpc.BidiStreamingServer[Req, Rsp]

// Demo_ServiceDesc is the grpc.ServiceDesc for Demo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Demo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simple",
			Handler:    _Demo_Simple_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Client",
			Handler:       _Demo_Client_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Server",
			Handler:       _Demo_Server_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Bidirectional",
			Handler:       _Demo_Bidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "demo.proto",
}
