// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: params.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Params_Form_FullMethodName   = "/api.Params/form"
	Params_Path_FullMethodName   = "/api.Params/path"
	Params_Query_FullMethodName  = "/api.Params/query"
	Params_Header_FullMethodName = "/api.Params/header"
	Params_Cookie_FullMethodName = "/api.Params/cookie"
)

// ParamsClient is the client API for Params service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParamsClient interface {
	Form(ctx context.Context, in *ParamsInForm, opts ...grpc.CallOption) (*ParamsInForm, error)
	Path(ctx context.Context, in *ParamsInPath, opts ...grpc.CallOption) (*ParamsInPath, error)
	Query(ctx context.Context, in *ParamsInQuery, opts ...grpc.CallOption) (*ParamsInQuery, error)
	Header(ctx context.Context, in *ParamsInHeader, opts ...grpc.CallOption) (*ParamsInHeader, error)
	Cookie(ctx context.Context, in *ParamsInCookie, opts ...grpc.CallOption) (*ParamsInCookie, error)
}

type paramsClient struct {
	cc grpc.ClientConnInterface
}

func NewParamsClient(cc grpc.ClientConnInterface) ParamsClient {
	return &paramsClient{cc}
}

func (c *paramsClient) Form(ctx context.Context, in *ParamsInForm, opts ...grpc.CallOption) (*ParamsInForm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamsInForm)
	err := c.cc.Invoke(ctx, Params_Form_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paramsClient) Path(ctx context.Context, in *ParamsInPath, opts ...grpc.CallOption) (*ParamsInPath, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamsInPath)
	err := c.cc.Invoke(ctx, Params_Path_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paramsClient) Query(ctx context.Context, in *ParamsInQuery, opts ...grpc.CallOption) (*ParamsInQuery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamsInQuery)
	err := c.cc.Invoke(ctx, Params_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paramsClient) Header(ctx context.Context, in *ParamsInHeader, opts ...grpc.CallOption) (*ParamsInHeader, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamsInHeader)
	err := c.cc.Invoke(ctx, Params_Header_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paramsClient) Cookie(ctx context.Context, in *ParamsInCookie, opts ...grpc.CallOption) (*ParamsInCookie, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamsInCookie)
	err := c.cc.Invoke(ctx, Params_Cookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParamsServer is the server API for Params service.
// All implementations should embed UnimplementedParamsServer
// for forward compatibility.
type ParamsServer interface {
	Form(context.Context, *ParamsInForm) (*ParamsInForm, error)
	Path(context.Context, *ParamsInPath) (*ParamsInPath, error)
	Query(context.Context, *ParamsInQuery) (*ParamsInQuery, error)
	Header(context.Context, *ParamsInHeader) (*ParamsInHeader, error)
	Cookie(context.Context, *ParamsInCookie) (*ParamsInCookie, error)
}

// UnimplementedParamsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParamsServer struct{}

func (UnimplementedParamsServer) Form(context.Context, *ParamsInForm) (*ParamsInForm, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Form not implemented")
}
func (UnimplementedParamsServer) Path(context.Context, *ParamsInPath) (*ParamsInPath, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Path not implemented")
}
func (UnimplementedParamsServer) Query(context.Context, *ParamsInQuery) (*ParamsInQuery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedParamsServer) Header(context.Context, *ParamsInHeader) (*ParamsInHeader, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Header not implemented")
}
func (UnimplementedParamsServer) Cookie(context.Context, *ParamsInCookie) (*ParamsInCookie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cookie not implemented")
}
func (UnimplementedParamsServer) testEmbeddedByValue() {}

// UnsafeParamsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParamsServer will
// result in compilation errors.
type UnsafeParamsServer interface {
	mustEmbedUnimplementedParamsServer()
}

func RegisterParamsServer(s grpc.ServiceRegistrar, srv ParamsServer) {
	// If the following call pancis, it indicates UnimplementedParamsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Params_ServiceDesc, srv)
}

func _Params_Form_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsInForm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParamsServer).Form(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Params_Form_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParamsServer).Form(ctx, req.(*ParamsInForm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Params_Path_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsInPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParamsServer).Path(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Params_Path_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParamsServer).Path(ctx, req.(*ParamsInPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Params_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsInQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParamsServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Params_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParamsServer).Query(ctx, req.(*ParamsInQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Params_Header_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsInHeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParamsServer).Header(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Params_Header_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParamsServer).Header(ctx, req.(*ParamsInHeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _Params_Cookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsInCookie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParamsServer).Cookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Params_Cookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParamsServer).Cookie(ctx, req.(*ParamsInCookie))
	}
	return interceptor(ctx, in, info, handler)
}

// Params_ServiceDesc is the grpc.ServiceDesc for Params service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Params_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Params",
	HandlerType: (*ParamsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "form",
			Handler:    _Params_Form_Handler,
		},
		{
			MethodName: "path",
			Handler:    _Params_Path_Handler,
		},
		{
			MethodName: "query",
			Handler:    _Params_Query_Handler,
		},
		{
			MethodName: "header",
			Handler:    _Params_Header_Handler,
		},
		{
			MethodName: "cookie",
			Handler:    _Params_Cookie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "params.proto",
}
