// Code generated by protoc-gen-go-protoapi. DO NOT EDIT!
// versions:
// - protoc-gen-go-protoapi v1.0.0
// - protoc                 v3.21.12
// source: params.proto
// create: 2025-03-21 16:47:25

package api

import (
	protoapi "github.com/hezof/protoapi"
	protojson "github.com/hezof/protojson"
	io "io"
)

func (x *ParamsInForm) DecodeField(r *protojson.JsonDecoder, f string) {
	switch f {
	case `bool`:
		protojson.DecodeBool(r, &x.Bool)
	case `int32`:
		protojson.DecodeInt32(r, &x.Int32)
	case `int64`:
		protojson.DecodeInt64(r, &x.Int64)
	case `uint32`:
		protojson.DecodeUint32(r, &x.Uint32)
	case `uint64`:
		protojson.DecodeUint64(r, &x.Uint64)
	case `float`:
		protojson.DecodeFloat(r, &x.Float)
	case `double`:
		protojson.DecodeDouble(r, &x.Double)
	case `string`:
		protojson.DecodeString(r, &x.String_)
	case `bytes`:
		protojson.DecodeBytes(r, &x.Bytes)
	case `genre`:
		protojson.DecodeEnum(r, &x.Genre)
	case `genre_name`:
		protojson.DecodeEnumName(r, &x.GenreName, Genre_value)
	case `bool_optional`:
		protojson.DecodeBoolOptional(r, &x.BoolOptional)
	case `int32_optional`:
		protojson.DecodeInt32Optional(r, &x.Int32Optional)
	case `int64_optional`:
		protojson.DecodeInt64Optional(r, &x.Int64Optional)
	case `uint32_optional`:
		protojson.DecodeUint32Optional(r, &x.Uint32Optional)
	case `uint64_optional`:
		protojson.DecodeUint64Optional(r, &x.Uint64Optional)
	case `float_optional`:
		protojson.DecodeFloatOptional(r, &x.FloatOptional)
	case `double_optional`:
		protojson.DecodeDoubleOptional(r, &x.DoubleOptional)
	case `string_optional`:
		protojson.DecodeStringOptional(r, &x.StringOptional)
	case `bytes_optional`:
		protojson.DecodeBytesOptional(r, &x.BytesOptional)
	case `genre_optional`:
		protojson.DecodeEnumOptional(r, &x.GenreOptional)
	case `genre_name_optional`:
		protojson.DecodeEnumNameOptional(r, &x.GenreNameOptional, Genre_value)
	case `bool_repeated`:
		protojson.DecodeBoolRepeated(r, &x.BoolRepeated)
	case `int32_repeated`:
		protojson.DecodeInt32Repeated(r, &x.Int32Repeated)
	case `int64_repeated`:
		protojson.DecodeInt64Repeated(r, &x.Int64Repeated)
	case `uint32_repeated`:
		protojson.DecodeUint32Repeated(r, &x.Uint32Repeated)
	case `uint64_repeated`:
		protojson.DecodeUint64Repeated(r, &x.Uint64Repeated)
	case `float_repeated`:
		protojson.DecodeFloatRepeated(r, &x.FloatRepeated)
	case `double_repeated`:
		protojson.DecodeDoubleRepeated(r, &x.DoubleRepeated)
	case `string_repeated`:
		protojson.DecodeStringRepeated(r, &x.StringRepeated)
	case `bytes_repeated`:
		protojson.DecodeBytesRepeated(r, &x.BytesRepeated)
	case `genre_repeated`:
		protojson.DecodeEnumRepeated(r, &x.GenreRepeated)
	case `genre_name_repeated`:
		protojson.DecodeEnumNameRepeated(r, &x.GenreNameRepeated, Genre_value)
	case `bool_map`:
		protojson.DecodeBoolMap(r, &x.BoolMap)
	case `int32_map`:
		protojson.DecodeInt32Map(r, &x.Int32Map)
	case `int64_map`:
		protojson.DecodeInt64Map(r, &x.Int64Map)
	case `uint32_map`:
		protojson.DecodeUint32Map(r, &x.Uint32Map)
	case `uint64_map`:
		protojson.DecodeUint64Map(r, &x.Uint64Map)
	case `float_map`:
		protojson.DecodeFloatMap(r, &x.FloatMap)
	case `double_map`:
		protojson.DecodeDoubleMap(r, &x.DoubleMap)
	case `string_map`:
		protojson.DecodeStringMap(r, &x.StringMap)
	case `bytes_map`:
		protojson.DecodeBytesMap(r, &x.BytesMap)
	case `genre_map`:
		protojson.DecodeEnumMap(r, &x.GenreMap)
	case `genre_name_map`:
		protojson.DecodeEnumNameMap(r, &x.GenreNameMap, Genre_value)
	}
}
func (x *ParamsInForm) EncodeField(w *protojson.JsonEncoder) {
	protojson.EncodeBool_OmitEmpty(w, `bool`, x.Bool)
	protojson.EncodeInt32_OmitEmpty(w, `int32`, x.Int32)
	protojson.EncodeInt64_OmitEmpty(w, `int64`, x.Int64)
	protojson.EncodeUint32_OmitEmpty(w, `uint32`, x.Uint32)
	protojson.EncodeUint64_OmitEmpty(w, `uint64`, x.Uint64)
	protojson.EncodeFloat_OmitEmpty(w, `float`, x.Float)
	protojson.EncodeDouble_OmitEmpty(w, `double`, x.Double)
	protojson.EncodeString_OmitEmpty(w, `string`, x.String_)
	protojson.EncodeBytes_OmitEmpty(w, `bytes`, x.Bytes)
	protojson.EncodeEnum_OmitEmpty(w, `genre`, x.Genre)
	protojson.EncodeEnumName_OmitEmpty(w, `genre_name`, x.GenreName, Genre_name)
	protojson.EncodeBoolOptional_OmitEmpty(w, `bool_optional`, x.BoolOptional)
	protojson.EncodeInt32Optional_OmitEmpty(w, `int32_optional`, x.Int32Optional)
	protojson.EncodeInt64Optional_OmitEmpty(w, `int64_optional`, x.Int64Optional)
	protojson.EncodeUint32Optional_OmitEmpty(w, `uint32_optional`, x.Uint32Optional)
	protojson.EncodeUint64Optional_OmitEmpty(w, `uint64_optional`, x.Uint64Optional)
	protojson.EncodeFloatOptional_OmitEmpty(w, `float_optional`, x.FloatOptional)
	protojson.EncodeDoubleOptional_OmitEmpty(w, `double_optional`, x.DoubleOptional)
	protojson.EncodeStringOptional_OmitEmpty(w, `string_optional`, x.StringOptional)
	protojson.EncodeBytesOptional_OmitEmpty(w, `bytes_optional`, x.BytesOptional)
	protojson.EncodeEnumOptional_OmitEmpty(w, `genre_optional`, x.GenreOptional)
	protojson.EncodeEnumNameOptional_OmitEmpty(w, `genre_name_optional`, x.GenreNameOptional, Genre_name)
	protojson.EncodeBoolRepeated_OmitEmpty(w, `bool_repeated`, x.BoolRepeated)
	protojson.EncodeInt32Repeated_OmitEmpty(w, `int32_repeated`, x.Int32Repeated)
	protojson.EncodeInt64Repeated_OmitEmpty(w, `int64_repeated`, x.Int64Repeated)
	protojson.EncodeUint32Repeated_OmitEmpty(w, `uint32_repeated`, x.Uint32Repeated)
	protojson.EncodeUint64Repeated_OmitEmpty(w, `uint64_repeated`, x.Uint64Repeated)
	protojson.EncodeFloatRepeated_OmitEmpty(w, `float_repeated`, x.FloatRepeated)
	protojson.EncodeDoubleRepeated_OmitEmpty(w, `double_repeated`, x.DoubleRepeated)
	protojson.EncodeStringRepeated_OmitEmpty(w, `string_repeated`, x.StringRepeated)
	protojson.EncodeBytesRepeated_OmitEmpty(w, `bytes_repeated`, x.BytesRepeated)
	protojson.EncodeEnumRepeated_OmitEmpty(w, `genre_repeated`, x.GenreRepeated)
	protojson.EncodeEnumNameRepeated_OmitEmpty(w, `genre_name_repeated`, x.GenreNameRepeated, Genre_name)
	protojson.EncodeBoolMap_OmitEmpty(w, `bool_map`, x.BoolMap)
	protojson.EncodeInt32Map_OmitEmpty(w, `int32_map`, x.Int32Map)
	protojson.EncodeInt64Map_OmitEmpty(w, `int64_map`, x.Int64Map)
	protojson.EncodeUint32Map_OmitEmpty(w, `uint32_map`, x.Uint32Map)
	protojson.EncodeUint64Map_OmitEmpty(w, `uint64_map`, x.Uint64Map)
	protojson.EncodeFloatMap_OmitEmpty(w, `float_map`, x.FloatMap)
	protojson.EncodeDoubleMap_OmitEmpty(w, `double_map`, x.DoubleMap)
	protojson.EncodeStringMap_OmitEmpty(w, `string_map`, x.StringMap)
	protojson.EncodeBytesMap_OmitEmpty(w, `bytes_map`, x.BytesMap)
	protojson.EncodeEnumMap_OmitEmpty(w, `genre_map`, x.GenreMap)
	protojson.EncodeEnumNameMap_OmitEmpty(w, `genre_name_map`, x.GenreNameMap, Genre_name)
}
func (x *ParamsInPath) DecodeField(r *protojson.JsonDecoder, f string) {
	switch f {
	case `bool`:
		protojson.DecodeBool(r, &x.Bool)
	case `int32`:
		protojson.DecodeInt32(r, &x.Int32)
	case `int64`:
		protojson.DecodeInt64(r, &x.Int64)
	case `uint32`:
		protojson.DecodeUint32(r, &x.Uint32)
	case `uint64`:
		protojson.DecodeUint64(r, &x.Uint64)
	case `float`:
		protojson.DecodeFloat(r, &x.Float)
	case `double`:
		protojson.DecodeDouble(r, &x.Double)
	case `string`:
		protojson.DecodeString(r, &x.String_)
	case `bytes`:
		protojson.DecodeBytes(r, &x.Bytes)
	case `genre`:
		protojson.DecodeEnum(r, &x.Genre)
	case `genre_name`:
		protojson.DecodeEnumName(r, &x.GenreName, Genre_value)
	case `bool_optional`:
		protojson.DecodeBoolOptional(r, &x.BoolOptional)
	case `int32_optional`:
		protojson.DecodeInt32Optional(r, &x.Int32Optional)
	case `int64_optional`:
		protojson.DecodeInt64Optional(r, &x.Int64Optional)
	case `uint32_optional`:
		protojson.DecodeUint32Optional(r, &x.Uint32Optional)
	case `uint64_optional`:
		protojson.DecodeUint64Optional(r, &x.Uint64Optional)
	case `float_optional`:
		protojson.DecodeFloatOptional(r, &x.FloatOptional)
	case `double_optional`:
		protojson.DecodeDoubleOptional(r, &x.DoubleOptional)
	case `string_optional`:
		protojson.DecodeStringOptional(r, &x.StringOptional)
	case `bytes_optional`:
		protojson.DecodeBytesOptional(r, &x.BytesOptional)
	case `genre_optional`:
		protojson.DecodeEnumOptional(r, &x.GenreOptional)
	case `genre_name_optional`:
		protojson.DecodeEnumNameOptional(r, &x.GenreNameOptional, Genre_value)
	case `bool_repeated`:
		protojson.DecodeBoolRepeated(r, &x.BoolRepeated)
	case `int32_repeated`:
		protojson.DecodeInt32Repeated(r, &x.Int32Repeated)
	case `int64_repeated`:
		protojson.DecodeInt64Repeated(r, &x.Int64Repeated)
	case `uint32_repeated`:
		protojson.DecodeUint32Repeated(r, &x.Uint32Repeated)
	case `uint64_repeated`:
		protojson.DecodeUint64Repeated(r, &x.Uint64Repeated)
	case `float_repeated`:
		protojson.DecodeFloatRepeated(r, &x.FloatRepeated)
	case `double_repeated`:
		protojson.DecodeDoubleRepeated(r, &x.DoubleRepeated)
	case `string_repeated`:
		protojson.DecodeStringRepeated(r, &x.StringRepeated)
	case `bytes_repeated`:
		protojson.DecodeBytesRepeated(r, &x.BytesRepeated)
	case `genre_repeated`:
		protojson.DecodeEnumRepeated(r, &x.GenreRepeated)
	case `genre_name_repeated`:
		protojson.DecodeEnumNameRepeated(r, &x.GenreNameRepeated, Genre_value)
	case `bool_map`:
		protojson.DecodeBoolMap(r, &x.BoolMap)
	case `int32_map`:
		protojson.DecodeInt32Map(r, &x.Int32Map)
	case `int64_map`:
		protojson.DecodeInt64Map(r, &x.Int64Map)
	case `uint32_map`:
		protojson.DecodeUint32Map(r, &x.Uint32Map)
	case `uint64_map`:
		protojson.DecodeUint64Map(r, &x.Uint64Map)
	case `float_map`:
		protojson.DecodeFloatMap(r, &x.FloatMap)
	case `double_map`:
		protojson.DecodeDoubleMap(r, &x.DoubleMap)
	case `string_map`:
		protojson.DecodeStringMap(r, &x.StringMap)
	case `bytes_map`:
		protojson.DecodeBytesMap(r, &x.BytesMap)
	case `genre_map`:
		protojson.DecodeEnumMap(r, &x.GenreMap)
	case `genre_name_map`:
		protojson.DecodeEnumNameMap(r, &x.GenreNameMap, Genre_value)
	}
}
func (x *ParamsInPath) EncodeField(w *protojson.JsonEncoder) {
	protojson.EncodeBool_OmitEmpty(w, `bool`, x.Bool)
	protojson.EncodeInt32_OmitEmpty(w, `int32`, x.Int32)
	protojson.EncodeInt64_OmitEmpty(w, `int64`, x.Int64)
	protojson.EncodeUint32_OmitEmpty(w, `uint32`, x.Uint32)
	protojson.EncodeUint64_OmitEmpty(w, `uint64`, x.Uint64)
	protojson.EncodeFloat_OmitEmpty(w, `float`, x.Float)
	protojson.EncodeDouble_OmitEmpty(w, `double`, x.Double)
	protojson.EncodeString_OmitEmpty(w, `string`, x.String_)
	protojson.EncodeBytes_OmitEmpty(w, `bytes`, x.Bytes)
	protojson.EncodeEnum_OmitEmpty(w, `genre`, x.Genre)
	protojson.EncodeEnumName_OmitEmpty(w, `genre_name`, x.GenreName, Genre_name)
	protojson.EncodeBoolOptional_OmitEmpty(w, `bool_optional`, x.BoolOptional)
	protojson.EncodeInt32Optional_OmitEmpty(w, `int32_optional`, x.Int32Optional)
	protojson.EncodeInt64Optional_OmitEmpty(w, `int64_optional`, x.Int64Optional)
	protojson.EncodeUint32Optional_OmitEmpty(w, `uint32_optional`, x.Uint32Optional)
	protojson.EncodeUint64Optional_OmitEmpty(w, `uint64_optional`, x.Uint64Optional)
	protojson.EncodeFloatOptional_OmitEmpty(w, `float_optional`, x.FloatOptional)
	protojson.EncodeDoubleOptional_OmitEmpty(w, `double_optional`, x.DoubleOptional)
	protojson.EncodeStringOptional_OmitEmpty(w, `string_optional`, x.StringOptional)
	protojson.EncodeBytesOptional_OmitEmpty(w, `bytes_optional`, x.BytesOptional)
	protojson.EncodeEnumOptional_OmitEmpty(w, `genre_optional`, x.GenreOptional)
	protojson.EncodeEnumNameOptional_OmitEmpty(w, `genre_name_optional`, x.GenreNameOptional, Genre_name)
	protojson.EncodeBoolRepeated_OmitEmpty(w, `bool_repeated`, x.BoolRepeated)
	protojson.EncodeInt32Repeated_OmitEmpty(w, `int32_repeated`, x.Int32Repeated)
	protojson.EncodeInt64Repeated_OmitEmpty(w, `int64_repeated`, x.Int64Repeated)
	protojson.EncodeUint32Repeated_OmitEmpty(w, `uint32_repeated`, x.Uint32Repeated)
	protojson.EncodeUint64Repeated_OmitEmpty(w, `uint64_repeated`, x.Uint64Repeated)
	protojson.EncodeFloatRepeated_OmitEmpty(w, `float_repeated`, x.FloatRepeated)
	protojson.EncodeDoubleRepeated_OmitEmpty(w, `double_repeated`, x.DoubleRepeated)
	protojson.EncodeStringRepeated_OmitEmpty(w, `string_repeated`, x.StringRepeated)
	protojson.EncodeBytesRepeated_OmitEmpty(w, `bytes_repeated`, x.BytesRepeated)
	protojson.EncodeEnumRepeated_OmitEmpty(w, `genre_repeated`, x.GenreRepeated)
	protojson.EncodeEnumNameRepeated_OmitEmpty(w, `genre_name_repeated`, x.GenreNameRepeated, Genre_name)
	protojson.EncodeBoolMap_OmitEmpty(w, `bool_map`, x.BoolMap)
	protojson.EncodeInt32Map_OmitEmpty(w, `int32_map`, x.Int32Map)
	protojson.EncodeInt64Map_OmitEmpty(w, `int64_map`, x.Int64Map)
	protojson.EncodeUint32Map_OmitEmpty(w, `uint32_map`, x.Uint32Map)
	protojson.EncodeUint64Map_OmitEmpty(w, `uint64_map`, x.Uint64Map)
	protojson.EncodeFloatMap_OmitEmpty(w, `float_map`, x.FloatMap)
	protojson.EncodeDoubleMap_OmitEmpty(w, `double_map`, x.DoubleMap)
	protojson.EncodeStringMap_OmitEmpty(w, `string_map`, x.StringMap)
	protojson.EncodeBytesMap_OmitEmpty(w, `bytes_map`, x.BytesMap)
	protojson.EncodeEnumMap_OmitEmpty(w, `genre_map`, x.GenreMap)
	protojson.EncodeEnumNameMap_OmitEmpty(w, `genre_name_map`, x.GenreNameMap, Genre_name)
}
func (x *ParamsInHeader) DecodeField(r *protojson.JsonDecoder, f string) {
	switch f {
	case `bool`:
		protojson.DecodeBool(r, &x.Bool)
	case `int32`:
		protojson.DecodeInt32(r, &x.Int32)
	case `int64`:
		protojson.DecodeInt64(r, &x.Int64)
	case `uint32`:
		protojson.DecodeUint32(r, &x.Uint32)
	case `uint64`:
		protojson.DecodeUint64(r, &x.Uint64)
	case `float`:
		protojson.DecodeFloat(r, &x.Float)
	case `double`:
		protojson.DecodeDouble(r, &x.Double)
	case `string`:
		protojson.DecodeString(r, &x.String_)
	case `bytes`:
		protojson.DecodeBytes(r, &x.Bytes)
	case `genre`:
		protojson.DecodeEnum(r, &x.Genre)
	case `genre_name`:
		protojson.DecodeEnumName(r, &x.GenreName, Genre_value)
	case `bool_optional`:
		protojson.DecodeBoolOptional(r, &x.BoolOptional)
	case `int32_optional`:
		protojson.DecodeInt32Optional(r, &x.Int32Optional)
	case `int64_optional`:
		protojson.DecodeInt64Optional(r, &x.Int64Optional)
	case `uint32_optional`:
		protojson.DecodeUint32Optional(r, &x.Uint32Optional)
	case `uint64_optional`:
		protojson.DecodeUint64Optional(r, &x.Uint64Optional)
	case `float_optional`:
		protojson.DecodeFloatOptional(r, &x.FloatOptional)
	case `double_optional`:
		protojson.DecodeDoubleOptional(r, &x.DoubleOptional)
	case `string_optional`:
		protojson.DecodeStringOptional(r, &x.StringOptional)
	case `bytes_optional`:
		protojson.DecodeBytesOptional(r, &x.BytesOptional)
	case `genre_optional`:
		protojson.DecodeEnumOptional(r, &x.GenreOptional)
	case `genre_name_optional`:
		protojson.DecodeEnumNameOptional(r, &x.GenreNameOptional, Genre_value)
	case `bool_repeated`:
		protojson.DecodeBoolRepeated(r, &x.BoolRepeated)
	case `int32_repeated`:
		protojson.DecodeInt32Repeated(r, &x.Int32Repeated)
	case `int64_repeated`:
		protojson.DecodeInt64Repeated(r, &x.Int64Repeated)
	case `uint32_repeated`:
		protojson.DecodeUint32Repeated(r, &x.Uint32Repeated)
	case `uint64_repeated`:
		protojson.DecodeUint64Repeated(r, &x.Uint64Repeated)
	case `float_repeated`:
		protojson.DecodeFloatRepeated(r, &x.FloatRepeated)
	case `double_repeated`:
		protojson.DecodeDoubleRepeated(r, &x.DoubleRepeated)
	case `string_repeated`:
		protojson.DecodeStringRepeated(r, &x.StringRepeated)
	case `bytes_repeated`:
		protojson.DecodeBytesRepeated(r, &x.BytesRepeated)
	case `genre_repeated`:
		protojson.DecodeEnumRepeated(r, &x.GenreRepeated)
	case `genre_name_repeated`:
		protojson.DecodeEnumNameRepeated(r, &x.GenreNameRepeated, Genre_value)
	case `bool_map`:
		protojson.DecodeBoolMap(r, &x.BoolMap)
	case `int32_map`:
		protojson.DecodeInt32Map(r, &x.Int32Map)
	case `int64_map`:
		protojson.DecodeInt64Map(r, &x.Int64Map)
	case `uint32_map`:
		protojson.DecodeUint32Map(r, &x.Uint32Map)
	case `uint64_map`:
		protojson.DecodeUint64Map(r, &x.Uint64Map)
	case `float_map`:
		protojson.DecodeFloatMap(r, &x.FloatMap)
	case `double_map`:
		protojson.DecodeDoubleMap(r, &x.DoubleMap)
	case `string_map`:
		protojson.DecodeStringMap(r, &x.StringMap)
	case `bytes_map`:
		protojson.DecodeBytesMap(r, &x.BytesMap)
	case `genre_map`:
		protojson.DecodeEnumMap(r, &x.GenreMap)
	case `genre_name_map`:
		protojson.DecodeEnumNameMap(r, &x.GenreNameMap, Genre_value)
	}
}
func (x *ParamsInHeader) EncodeField(w *protojson.JsonEncoder) {
	protojson.EncodeBool_OmitEmpty(w, `bool`, x.Bool)
	protojson.EncodeInt32_OmitEmpty(w, `int32`, x.Int32)
	protojson.EncodeInt64_OmitEmpty(w, `int64`, x.Int64)
	protojson.EncodeUint32_OmitEmpty(w, `uint32`, x.Uint32)
	protojson.EncodeUint64_OmitEmpty(w, `uint64`, x.Uint64)
	protojson.EncodeFloat_OmitEmpty(w, `float`, x.Float)
	protojson.EncodeDouble_OmitEmpty(w, `double`, x.Double)
	protojson.EncodeString_OmitEmpty(w, `string`, x.String_)
	protojson.EncodeBytes_OmitEmpty(w, `bytes`, x.Bytes)
	protojson.EncodeEnum_OmitEmpty(w, `genre`, x.Genre)
	protojson.EncodeEnumName_OmitEmpty(w, `genre_name`, x.GenreName, Genre_name)
	protojson.EncodeBoolOptional_OmitEmpty(w, `bool_optional`, x.BoolOptional)
	protojson.EncodeInt32Optional_OmitEmpty(w, `int32_optional`, x.Int32Optional)
	protojson.EncodeInt64Optional_OmitEmpty(w, `int64_optional`, x.Int64Optional)
	protojson.EncodeUint32Optional_OmitEmpty(w, `uint32_optional`, x.Uint32Optional)
	protojson.EncodeUint64Optional_OmitEmpty(w, `uint64_optional`, x.Uint64Optional)
	protojson.EncodeFloatOptional_OmitEmpty(w, `float_optional`, x.FloatOptional)
	protojson.EncodeDoubleOptional_OmitEmpty(w, `double_optional`, x.DoubleOptional)
	protojson.EncodeStringOptional_OmitEmpty(w, `string_optional`, x.StringOptional)
	protojson.EncodeBytesOptional_OmitEmpty(w, `bytes_optional`, x.BytesOptional)
	protojson.EncodeEnumOptional_OmitEmpty(w, `genre_optional`, x.GenreOptional)
	protojson.EncodeEnumNameOptional_OmitEmpty(w, `genre_name_optional`, x.GenreNameOptional, Genre_name)
	protojson.EncodeBoolRepeated_OmitEmpty(w, `bool_repeated`, x.BoolRepeated)
	protojson.EncodeInt32Repeated_OmitEmpty(w, `int32_repeated`, x.Int32Repeated)
	protojson.EncodeInt64Repeated_OmitEmpty(w, `int64_repeated`, x.Int64Repeated)
	protojson.EncodeUint32Repeated_OmitEmpty(w, `uint32_repeated`, x.Uint32Repeated)
	protojson.EncodeUint64Repeated_OmitEmpty(w, `uint64_repeated`, x.Uint64Repeated)
	protojson.EncodeFloatRepeated_OmitEmpty(w, `float_repeated`, x.FloatRepeated)
	protojson.EncodeDoubleRepeated_OmitEmpty(w, `double_repeated`, x.DoubleRepeated)
	protojson.EncodeStringRepeated_OmitEmpty(w, `string_repeated`, x.StringRepeated)
	protojson.EncodeBytesRepeated_OmitEmpty(w, `bytes_repeated`, x.BytesRepeated)
	protojson.EncodeEnumRepeated_OmitEmpty(w, `genre_repeated`, x.GenreRepeated)
	protojson.EncodeEnumNameRepeated_OmitEmpty(w, `genre_name_repeated`, x.GenreNameRepeated, Genre_name)
	protojson.EncodeBoolMap_OmitEmpty(w, `bool_map`, x.BoolMap)
	protojson.EncodeInt32Map_OmitEmpty(w, `int32_map`, x.Int32Map)
	protojson.EncodeInt64Map_OmitEmpty(w, `int64_map`, x.Int64Map)
	protojson.EncodeUint32Map_OmitEmpty(w, `uint32_map`, x.Uint32Map)
	protojson.EncodeUint64Map_OmitEmpty(w, `uint64_map`, x.Uint64Map)
	protojson.EncodeFloatMap_OmitEmpty(w, `float_map`, x.FloatMap)
	protojson.EncodeDoubleMap_OmitEmpty(w, `double_map`, x.DoubleMap)
	protojson.EncodeStringMap_OmitEmpty(w, `string_map`, x.StringMap)
	protojson.EncodeBytesMap_OmitEmpty(w, `bytes_map`, x.BytesMap)
	protojson.EncodeEnumMap_OmitEmpty(w, `genre_map`, x.GenreMap)
	protojson.EncodeEnumNameMap_OmitEmpty(w, `genre_name_map`, x.GenreNameMap, Genre_name)
}
func (x *ParamsInQuery) DecodeField(r *protojson.JsonDecoder, f string) {
	switch f {
	case `bool`:
		protojson.DecodeBool(r, &x.Bool)
	case `int32`:
		protojson.DecodeInt32(r, &x.Int32)
	case `int64`:
		protojson.DecodeInt64(r, &x.Int64)
	case `uint32`:
		protojson.DecodeUint32(r, &x.Uint32)
	case `uint64`:
		protojson.DecodeUint64(r, &x.Uint64)
	case `float`:
		protojson.DecodeFloat(r, &x.Float)
	case `double`:
		protojson.DecodeDouble(r, &x.Double)
	case `string`:
		protojson.DecodeString(r, &x.String_)
	case `bytes`:
		protojson.DecodeBytes(r, &x.Bytes)
	case `genre`:
		protojson.DecodeEnum(r, &x.Genre)
	case `genre_name`:
		protojson.DecodeEnumName(r, &x.GenreName, Genre_value)
	case `bool_optional`:
		protojson.DecodeBoolOptional(r, &x.BoolOptional)
	case `int32_optional`:
		protojson.DecodeInt32Optional(r, &x.Int32Optional)
	case `int64_optional`:
		protojson.DecodeInt64Optional(r, &x.Int64Optional)
	case `uint32_optional`:
		protojson.DecodeUint32Optional(r, &x.Uint32Optional)
	case `uint64_optional`:
		protojson.DecodeUint64Optional(r, &x.Uint64Optional)
	case `float_optional`:
		protojson.DecodeFloatOptional(r, &x.FloatOptional)
	case `double_optional`:
		protojson.DecodeDoubleOptional(r, &x.DoubleOptional)
	case `string_optional`:
		protojson.DecodeStringOptional(r, &x.StringOptional)
	case `bytes_optional`:
		protojson.DecodeBytesOptional(r, &x.BytesOptional)
	case `genre_optional`:
		protojson.DecodeEnumOptional(r, &x.GenreOptional)
	case `genre_name_optional`:
		protojson.DecodeEnumNameOptional(r, &x.GenreNameOptional, Genre_value)
	case `bool_repeated`:
		protojson.DecodeBoolRepeated(r, &x.BoolRepeated)
	case `int32_repeated`:
		protojson.DecodeInt32Repeated(r, &x.Int32Repeated)
	case `int64_repeated`:
		protojson.DecodeInt64Repeated(r, &x.Int64Repeated)
	case `uint32_repeated`:
		protojson.DecodeUint32Repeated(r, &x.Uint32Repeated)
	case `uint64_repeated`:
		protojson.DecodeUint64Repeated(r, &x.Uint64Repeated)
	case `float_repeated`:
		protojson.DecodeFloatRepeated(r, &x.FloatRepeated)
	case `double_repeated`:
		protojson.DecodeDoubleRepeated(r, &x.DoubleRepeated)
	case `string_repeated`:
		protojson.DecodeStringRepeated(r, &x.StringRepeated)
	case `bytes_repeated`:
		protojson.DecodeBytesRepeated(r, &x.BytesRepeated)
	case `genre_repeated`:
		protojson.DecodeEnumRepeated(r, &x.GenreRepeated)
	case `genre_name_repeated`:
		protojson.DecodeEnumNameRepeated(r, &x.GenreNameRepeated, Genre_value)
	case `bool_map`:
		protojson.DecodeBoolMap(r, &x.BoolMap)
	case `int32_map`:
		protojson.DecodeInt32Map(r, &x.Int32Map)
	case `int64_map`:
		protojson.DecodeInt64Map(r, &x.Int64Map)
	case `uint32_map`:
		protojson.DecodeUint32Map(r, &x.Uint32Map)
	case `uint64_map`:
		protojson.DecodeUint64Map(r, &x.Uint64Map)
	case `float_map`:
		protojson.DecodeFloatMap(r, &x.FloatMap)
	case `double_map`:
		protojson.DecodeDoubleMap(r, &x.DoubleMap)
	case `string_map`:
		protojson.DecodeStringMap(r, &x.StringMap)
	case `bytes_map`:
		protojson.DecodeBytesMap(r, &x.BytesMap)
	case `genre_map`:
		protojson.DecodeEnumMap(r, &x.GenreMap)
	case `genre_name_map`:
		protojson.DecodeEnumNameMap(r, &x.GenreNameMap, Genre_value)
	}
}
func (x *ParamsInQuery) EncodeField(w *protojson.JsonEncoder) {
	protojson.EncodeBool_OmitEmpty(w, `bool`, x.Bool)
	protojson.EncodeInt32_OmitEmpty(w, `int32`, x.Int32)
	protojson.EncodeInt64_OmitEmpty(w, `int64`, x.Int64)
	protojson.EncodeUint32_OmitEmpty(w, `uint32`, x.Uint32)
	protojson.EncodeUint64_OmitEmpty(w, `uint64`, x.Uint64)
	protojson.EncodeFloat_OmitEmpty(w, `float`, x.Float)
	protojson.EncodeDouble_OmitEmpty(w, `double`, x.Double)
	protojson.EncodeString_OmitEmpty(w, `string`, x.String_)
	protojson.EncodeBytes_OmitEmpty(w, `bytes`, x.Bytes)
	protojson.EncodeEnum_OmitEmpty(w, `genre`, x.Genre)
	protojson.EncodeEnumName_OmitEmpty(w, `genre_name`, x.GenreName, Genre_name)
	protojson.EncodeBoolOptional_OmitEmpty(w, `bool_optional`, x.BoolOptional)
	protojson.EncodeInt32Optional_OmitEmpty(w, `int32_optional`, x.Int32Optional)
	protojson.EncodeInt64Optional_OmitEmpty(w, `int64_optional`, x.Int64Optional)
	protojson.EncodeUint32Optional_OmitEmpty(w, `uint32_optional`, x.Uint32Optional)
	protojson.EncodeUint64Optional_OmitEmpty(w, `uint64_optional`, x.Uint64Optional)
	protojson.EncodeFloatOptional_OmitEmpty(w, `float_optional`, x.FloatOptional)
	protojson.EncodeDoubleOptional_OmitEmpty(w, `double_optional`, x.DoubleOptional)
	protojson.EncodeStringOptional_OmitEmpty(w, `string_optional`, x.StringOptional)
	protojson.EncodeBytesOptional_OmitEmpty(w, `bytes_optional`, x.BytesOptional)
	protojson.EncodeEnumOptional_OmitEmpty(w, `genre_optional`, x.GenreOptional)
	protojson.EncodeEnumNameOptional_OmitEmpty(w, `genre_name_optional`, x.GenreNameOptional, Genre_name)
	protojson.EncodeBoolRepeated_OmitEmpty(w, `bool_repeated`, x.BoolRepeated)
	protojson.EncodeInt32Repeated_OmitEmpty(w, `int32_repeated`, x.Int32Repeated)
	protojson.EncodeInt64Repeated_OmitEmpty(w, `int64_repeated`, x.Int64Repeated)
	protojson.EncodeUint32Repeated_OmitEmpty(w, `uint32_repeated`, x.Uint32Repeated)
	protojson.EncodeUint64Repeated_OmitEmpty(w, `uint64_repeated`, x.Uint64Repeated)
	protojson.EncodeFloatRepeated_OmitEmpty(w, `float_repeated`, x.FloatRepeated)
	protojson.EncodeDoubleRepeated_OmitEmpty(w, `double_repeated`, x.DoubleRepeated)
	protojson.EncodeStringRepeated_OmitEmpty(w, `string_repeated`, x.StringRepeated)
	protojson.EncodeBytesRepeated_OmitEmpty(w, `bytes_repeated`, x.BytesRepeated)
	protojson.EncodeEnumRepeated_OmitEmpty(w, `genre_repeated`, x.GenreRepeated)
	protojson.EncodeEnumNameRepeated_OmitEmpty(w, `genre_name_repeated`, x.GenreNameRepeated, Genre_name)
	protojson.EncodeBoolMap_OmitEmpty(w, `bool_map`, x.BoolMap)
	protojson.EncodeInt32Map_OmitEmpty(w, `int32_map`, x.Int32Map)
	protojson.EncodeInt64Map_OmitEmpty(w, `int64_map`, x.Int64Map)
	protojson.EncodeUint32Map_OmitEmpty(w, `uint32_map`, x.Uint32Map)
	protojson.EncodeUint64Map_OmitEmpty(w, `uint64_map`, x.Uint64Map)
	protojson.EncodeFloatMap_OmitEmpty(w, `float_map`, x.FloatMap)
	protojson.EncodeDoubleMap_OmitEmpty(w, `double_map`, x.DoubleMap)
	protojson.EncodeStringMap_OmitEmpty(w, `string_map`, x.StringMap)
	protojson.EncodeBytesMap_OmitEmpty(w, `bytes_map`, x.BytesMap)
	protojson.EncodeEnumMap_OmitEmpty(w, `genre_map`, x.GenreMap)
	protojson.EncodeEnumNameMap_OmitEmpty(w, `genre_name_map`, x.GenreNameMap, Genre_name)
}
func (x *ParamsInCookie) DecodeField(r *protojson.JsonDecoder, f string) {
	switch f {
	case `bool`:
		protojson.DecodeBool(r, &x.Bool)
	case `int32`:
		protojson.DecodeInt32(r, &x.Int32)
	case `int64`:
		protojson.DecodeInt64(r, &x.Int64)
	case `uint32`:
		protojson.DecodeUint32(r, &x.Uint32)
	case `uint64`:
		protojson.DecodeUint64(r, &x.Uint64)
	case `float`:
		protojson.DecodeFloat(r, &x.Float)
	case `double`:
		protojson.DecodeDouble(r, &x.Double)
	case `string`:
		protojson.DecodeString(r, &x.String_)
	case `bytes`:
		protojson.DecodeBytes(r, &x.Bytes)
	case `genre`:
		protojson.DecodeEnum(r, &x.Genre)
	case `genre_name`:
		protojson.DecodeEnumName(r, &x.GenreName, Genre_value)
	case `bool_optional`:
		protojson.DecodeBoolOptional(r, &x.BoolOptional)
	case `int32_optional`:
		protojson.DecodeInt32Optional(r, &x.Int32Optional)
	case `int64_optional`:
		protojson.DecodeInt64Optional(r, &x.Int64Optional)
	case `uint32_optional`:
		protojson.DecodeUint32Optional(r, &x.Uint32Optional)
	case `uint64_optional`:
		protojson.DecodeUint64Optional(r, &x.Uint64Optional)
	case `float_optional`:
		protojson.DecodeFloatOptional(r, &x.FloatOptional)
	case `double_optional`:
		protojson.DecodeDoubleOptional(r, &x.DoubleOptional)
	case `string_optional`:
		protojson.DecodeStringOptional(r, &x.StringOptional)
	case `bytes_optional`:
		protojson.DecodeBytesOptional(r, &x.BytesOptional)
	case `genre_optional`:
		protojson.DecodeEnumOptional(r, &x.GenreOptional)
	case `genre_name_optional`:
		protojson.DecodeEnumNameOptional(r, &x.GenreNameOptional, Genre_value)
	case `bool_repeated`:
		protojson.DecodeBoolRepeated(r, &x.BoolRepeated)
	case `int32_repeated`:
		protojson.DecodeInt32Repeated(r, &x.Int32Repeated)
	case `int64_repeated`:
		protojson.DecodeInt64Repeated(r, &x.Int64Repeated)
	case `uint32_repeated`:
		protojson.DecodeUint32Repeated(r, &x.Uint32Repeated)
	case `uint64_repeated`:
		protojson.DecodeUint64Repeated(r, &x.Uint64Repeated)
	case `float_repeated`:
		protojson.DecodeFloatRepeated(r, &x.FloatRepeated)
	case `double_repeated`:
		protojson.DecodeDoubleRepeated(r, &x.DoubleRepeated)
	case `string_repeated`:
		protojson.DecodeStringRepeated(r, &x.StringRepeated)
	case `bytes_repeated`:
		protojson.DecodeBytesRepeated(r, &x.BytesRepeated)
	case `genre_repeated`:
		protojson.DecodeEnumRepeated(r, &x.GenreRepeated)
	case `genre_name_repeated`:
		protojson.DecodeEnumNameRepeated(r, &x.GenreNameRepeated, Genre_value)
	case `bool_map`:
		protojson.DecodeBoolMap(r, &x.BoolMap)
	case `int32_map`:
		protojson.DecodeInt32Map(r, &x.Int32Map)
	case `int64_map`:
		protojson.DecodeInt64Map(r, &x.Int64Map)
	case `uint32_map`:
		protojson.DecodeUint32Map(r, &x.Uint32Map)
	case `uint64_map`:
		protojson.DecodeUint64Map(r, &x.Uint64Map)
	case `float_map`:
		protojson.DecodeFloatMap(r, &x.FloatMap)
	case `double_map`:
		protojson.DecodeDoubleMap(r, &x.DoubleMap)
	case `string_map`:
		protojson.DecodeStringMap(r, &x.StringMap)
	case `bytes_map`:
		protojson.DecodeBytesMap(r, &x.BytesMap)
	case `genre_map`:
		protojson.DecodeEnumMap(r, &x.GenreMap)
	case `genre_name_map`:
		protojson.DecodeEnumNameMap(r, &x.GenreNameMap, Genre_value)
	}
}
func (x *ParamsInCookie) EncodeField(w *protojson.JsonEncoder) {
	protojson.EncodeBool_OmitEmpty(w, `bool`, x.Bool)
	protojson.EncodeInt32_OmitEmpty(w, `int32`, x.Int32)
	protojson.EncodeInt64_OmitEmpty(w, `int64`, x.Int64)
	protojson.EncodeUint32_OmitEmpty(w, `uint32`, x.Uint32)
	protojson.EncodeUint64_OmitEmpty(w, `uint64`, x.Uint64)
	protojson.EncodeFloat_OmitEmpty(w, `float`, x.Float)
	protojson.EncodeDouble_OmitEmpty(w, `double`, x.Double)
	protojson.EncodeString_OmitEmpty(w, `string`, x.String_)
	protojson.EncodeBytes_OmitEmpty(w, `bytes`, x.Bytes)
	protojson.EncodeEnum_OmitEmpty(w, `genre`, x.Genre)
	protojson.EncodeEnumName_OmitEmpty(w, `genre_name`, x.GenreName, Genre_name)
	protojson.EncodeBoolOptional_OmitEmpty(w, `bool_optional`, x.BoolOptional)
	protojson.EncodeInt32Optional_OmitEmpty(w, `int32_optional`, x.Int32Optional)
	protojson.EncodeInt64Optional_OmitEmpty(w, `int64_optional`, x.Int64Optional)
	protojson.EncodeUint32Optional_OmitEmpty(w, `uint32_optional`, x.Uint32Optional)
	protojson.EncodeUint64Optional_OmitEmpty(w, `uint64_optional`, x.Uint64Optional)
	protojson.EncodeFloatOptional_OmitEmpty(w, `float_optional`, x.FloatOptional)
	protojson.EncodeDoubleOptional_OmitEmpty(w, `double_optional`, x.DoubleOptional)
	protojson.EncodeStringOptional_OmitEmpty(w, `string_optional`, x.StringOptional)
	protojson.EncodeBytesOptional_OmitEmpty(w, `bytes_optional`, x.BytesOptional)
	protojson.EncodeEnumOptional_OmitEmpty(w, `genre_optional`, x.GenreOptional)
	protojson.EncodeEnumNameOptional_OmitEmpty(w, `genre_name_optional`, x.GenreNameOptional, Genre_name)
	protojson.EncodeBoolRepeated_OmitEmpty(w, `bool_repeated`, x.BoolRepeated)
	protojson.EncodeInt32Repeated_OmitEmpty(w, `int32_repeated`, x.Int32Repeated)
	protojson.EncodeInt64Repeated_OmitEmpty(w, `int64_repeated`, x.Int64Repeated)
	protojson.EncodeUint32Repeated_OmitEmpty(w, `uint32_repeated`, x.Uint32Repeated)
	protojson.EncodeUint64Repeated_OmitEmpty(w, `uint64_repeated`, x.Uint64Repeated)
	protojson.EncodeFloatRepeated_OmitEmpty(w, `float_repeated`, x.FloatRepeated)
	protojson.EncodeDoubleRepeated_OmitEmpty(w, `double_repeated`, x.DoubleRepeated)
	protojson.EncodeStringRepeated_OmitEmpty(w, `string_repeated`, x.StringRepeated)
	protojson.EncodeBytesRepeated_OmitEmpty(w, `bytes_repeated`, x.BytesRepeated)
	protojson.EncodeEnumRepeated_OmitEmpty(w, `genre_repeated`, x.GenreRepeated)
	protojson.EncodeEnumNameRepeated_OmitEmpty(w, `genre_name_repeated`, x.GenreNameRepeated, Genre_name)
	protojson.EncodeBoolMap_OmitEmpty(w, `bool_map`, x.BoolMap)
	protojson.EncodeInt32Map_OmitEmpty(w, `int32_map`, x.Int32Map)
	protojson.EncodeInt64Map_OmitEmpty(w, `int64_map`, x.Int64Map)
	protojson.EncodeUint32Map_OmitEmpty(w, `uint32_map`, x.Uint32Map)
	protojson.EncodeUint64Map_OmitEmpty(w, `uint64_map`, x.Uint64Map)
	protojson.EncodeFloatMap_OmitEmpty(w, `float_map`, x.FloatMap)
	protojson.EncodeDoubleMap_OmitEmpty(w, `double_map`, x.DoubleMap)
	protojson.EncodeStringMap_OmitEmpty(w, `string_map`, x.StringMap)
	protojson.EncodeBytesMap_OmitEmpty(w, `bytes_map`, x.BytesMap)
	protojson.EncodeEnumMap_OmitEmpty(w, `genre_map`, x.GenreMap)
	protojson.EncodeEnumNameMap_OmitEmpty(w, `genre_name_map`, x.GenreNameMap, Genre_name)
}
func ParamsRegistry(impl interface{}, aspects []protoapi.ServiceAspect) *protoapi.ServiceSetting {
	ret := new(protoapi.ServiceSetting)
	ret.Impl = impl
	ret.Desc = &Params_ServiceDesc
	ret.HttpOnly = true
	ret.Aspects = aspects
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBlBhcmFtcxoEZm9ybTJCChDor7vlj5Zmb3Jt5Y+C5pWwEhvpgJrov4dmb3JtL2JvZHnkvKDpgJLlj4LmlbAqDC9wYXJhbXMvZm9ybWgBcMgBSgYKBGJvb2xKBwoFaW50MzJKBwoFaW50NjRKCAoGdWludDMySggKBnVpbnQ2NEoHCgVmbG9hdEoICgZkb3VibGVKCAoGc3RyaW5nSgcKBWJ5dGVzSgcKBWdlbnJlSgwKCmdlbnJlX25hbWVKDwoNYm9vbF9vcHRpb25hbEoQCg5pbnQzMl9vcHRpb25hbEoQCg5pbnQ2NF9vcHRpb25hbEoRCg91aW50MzJfb3B0aW9uYWxKEQoPdWludDY0X29wdGlvbmFsShAKDmZsb2F0X29wdGlvbmFsShEKD2RvdWJsZV9vcHRpb25hbEoRCg9zdHJpbmdfb3B0aW9uYWxKEAoOYnl0ZXNfb3B0aW9uYWxKEAoOZ2VucmVfb3B0aW9uYWxKFQoTZ2VucmVfbmFtZV9vcHRpb25hbEoPCg1ib29sX3JlcGVhdGVkShAKDmludDMyX3JlcGVhdGVkShAKDmludDY0X3JlcGVhdGVkShEKD3VpbnQzMl9yZXBlYXRlZEoRCg91aW50NjRfcmVwZWF0ZWRKEAoOZmxvYXRfcmVwZWF0ZWRKEQoPZG91YmxlX3JlcGVhdGVkShEKD3N0cmluZ19yZXBlYXRlZEoQCg5ieXRlc19yZXBlYXRlZEoQCg5nZW5yZV9yZXBlYXRlZEoVChNnZW5yZV9uYW1lX3JlcGVhdGVkSgoKCGJvb2xfbWFwSgsKCWludDMyX21hcEoLCglpbnQ2NF9tYXBKDAoKdWludDMyX21hcEoMCgp1aW50NjRfbWFwSgsKCWZsb2F0X21hcEoMCgpkb3VibGVfbWFwSgwKCnN0cmluZ19tYXBKCwoJYnl0ZXNfbWFwSgsKCWdlbnJlX21hcEoQCg5nZW5yZV9uYW1lX21hcA==`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(ParamsInForm)
			if err = protoapi.ParamBool(pc.FormValue, `bool`, &req.Bool); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32(pc.FormValue, `int32`, &req.Int32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64(pc.FormValue, `int64`, &req.Int64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32(pc.FormValue, `uint32`, &req.Uint32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64(pc.FormValue, `uint64`, &req.Uint64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloat(pc.FormValue, `float`, &req.Float); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDouble(pc.FormValue, `double`, &req.Double); err != nil {
				return nil, err
			}
			if err = protoapi.ParamString(pc.FormValue, `string`, &req.String_); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytes(pc.FormValue, `bytes`, &req.Bytes); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnum(pc.FormValue, `genre`, &req.Genre); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumName(pc.FormValue, `genre_name`, &req.GenreName, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolOptional(pc.FormValue, `bool_optional`, &req.BoolOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Optional(pc.FormValue, `int32_optional`, &req.Int32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Optional(pc.FormValue, `int64_optional`, &req.Int64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Optional(pc.FormValue, `uint32_optional`, &req.Uint32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Optional(pc.FormValue, `uint64_optional`, &req.Uint64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatOptional(pc.FormValue, `float_optional`, &req.FloatOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleOptional(pc.FormValue, `double_optional`, &req.DoubleOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringOptional(pc.FormValue, `string_optional`, &req.StringOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesOptional(pc.FormValue, `bytes_optional`, &req.BytesOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumOptional(pc.FormValue, `genre_optional`, &req.GenreOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameOptional(pc.FormValue, `genre_name_optional`, &req.GenreNameOptional, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolRepeated(pc.FormValueRepeated, `bool_repeated`, &req.BoolRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Repeated(pc.FormValueRepeated, `int32_repeated`, &req.Int32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Repeated(pc.FormValueRepeated, `int64_repeated`, &req.Int64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Repeated(pc.FormValueRepeated, `uint32_repeated`, &req.Uint32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Repeated(pc.FormValueRepeated, `uint64_repeated`, &req.Uint64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatRepeated(pc.FormValueRepeated, `float_repeated`, &req.FloatRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleRepeated(pc.FormValueRepeated, `double_repeated`, &req.DoubleRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringRepeated(pc.FormValueRepeated, `string_repeated`, &req.StringRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesRepeated(pc.FormValueRepeated, `bytes_repeated`, &req.BytesRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumRepeated(pc.FormValueRepeated, `genre_repeated`, &req.GenreRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameRepeated(pc.FormValueRepeated, `genre_name_repeated`, &req.GenreNameRepeated, Genre_value, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolMap(pc.FormValueMap, `bool_map`, &req.BoolMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Map(pc.FormValueMap, `int32_map`, &req.Int32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Map(pc.FormValueMap, `int64_map`, &req.Int64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Map(pc.FormValueMap, `uint32_map`, &req.Uint32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Map(pc.FormValueMap, `uint64_map`, &req.Uint64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatMap(pc.FormValueMap, `float_map`, &req.FloatMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleMap(pc.FormValueMap, `double_map`, &req.DoubleMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringMap(pc.FormValueMap, `string_map`, &req.StringMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesMap(pc.FormValueMap, `bytes_map`, &req.BytesMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumMap(pc.FormValueMap, `genre_map`, &req.GenreMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameMap(pc.FormValueMap, `genre_name_map`, &req.GenreNameMap, Genre_value, false); err != nil {
				return nil, err
			}
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				rsp, err = set.Service.Impl.(ParamsServer).Form(ctx, req)
			}
			return protoapi.AfterAspect(set, idx, ctx, req, rsp, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBlBhcmFtcxoEcGF0aDJYChDor7vlj5ZwYXRo5Y+C5pWwEhbpgJrov4dwYXRo5Lyg6YCS5Y+C5pWwKicvcGFyYW1zL3BhdGgvOmdlbnJlX21hcC86Z2VucmVfbmFtZV9tYXBoAnDIAUoGCgRib29sSgcKBWludDMySgcKBWludDY0SggKBnVpbnQzMkoICgZ1aW50NjRKBwoFZmxvYXRKCAoGZG91YmxlSggKBnN0cmluZ0oHCgVieXRlc0oHCgVnZW5yZUoMCgpnZW5yZV9uYW1lSg8KDWJvb2xfb3B0aW9uYWxKEAoOaW50MzJfb3B0aW9uYWxKEAoOaW50NjRfb3B0aW9uYWxKEQoPdWludDMyX29wdGlvbmFsShEKD3VpbnQ2NF9vcHRpb25hbEoQCg5mbG9hdF9vcHRpb25hbEoRCg9kb3VibGVfb3B0aW9uYWxKEQoPc3RyaW5nX29wdGlvbmFsShAKDmJ5dGVzX29wdGlvbmFsShAKDmdlbnJlX29wdGlvbmFsShUKE2dlbnJlX25hbWVfb3B0aW9uYWxKDwoNYm9vbF9yZXBlYXRlZEoQCg5pbnQzMl9yZXBlYXRlZEoQCg5pbnQ2NF9yZXBlYXRlZEoRCg91aW50MzJfcmVwZWF0ZWRKEQoPdWludDY0X3JlcGVhdGVkShAKDmZsb2F0X3JlcGVhdGVkShEKD2RvdWJsZV9yZXBlYXRlZEoRCg9zdHJpbmdfcmVwZWF0ZWRKEAoOYnl0ZXNfcmVwZWF0ZWRKEAoOZ2VucmVfcmVwZWF0ZWRKFQoTZ2VucmVfbmFtZV9yZXBlYXRlZEoKCghib29sX21hcEoLCglpbnQzMl9tYXBKCwoJaW50NjRfbWFwSgwKCnVpbnQzMl9tYXBKDAoKdWludDY0X21hcEoLCglmbG9hdF9tYXBKDAoKZG91YmxlX21hcEoMCgpzdHJpbmdfbWFwSgsKCWJ5dGVzX21hcEoLCglnZW5yZV9tYXBKEAoOZ2VucmVfbmFtZV9tYXA=`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(ParamsInPath)
			if err = protoapi.ParamBool(pc.PathValue, `bool`, &req.Bool); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32(pc.PathValue, `int32`, &req.Int32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64(pc.PathValue, `int64`, &req.Int64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32(pc.PathValue, `uint32`, &req.Uint32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64(pc.PathValue, `uint64`, &req.Uint64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloat(pc.PathValue, `float`, &req.Float); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDouble(pc.PathValue, `double`, &req.Double); err != nil {
				return nil, err
			}
			if err = protoapi.ParamString(pc.PathValue, `string`, &req.String_); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytes(pc.PathValue, `bytes`, &req.Bytes); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnum(pc.PathValue, `genre`, &req.Genre); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumName(pc.PathValue, `genre_name`, &req.GenreName, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolOptional(pc.PathValue, `bool_optional`, &req.BoolOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Optional(pc.PathValue, `int32_optional`, &req.Int32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Optional(pc.PathValue, `int64_optional`, &req.Int64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Optional(pc.PathValue, `uint32_optional`, &req.Uint32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Optional(pc.PathValue, `uint64_optional`, &req.Uint64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatOptional(pc.PathValue, `float_optional`, &req.FloatOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleOptional(pc.PathValue, `double_optional`, &req.DoubleOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringOptional(pc.PathValue, `string_optional`, &req.StringOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesOptional(pc.PathValue, `bytes_optional`, &req.BytesOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumOptional(pc.PathValue, `genre_optional`, &req.GenreOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameOptional(pc.PathValue, `genre_name_optional`, &req.GenreNameOptional, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolRepeated(pc.PathValueRepeated, `bool_repeated`, &req.BoolRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Repeated(pc.PathValueRepeated, `int32_repeated`, &req.Int32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Repeated(pc.PathValueRepeated, `int64_repeated`, &req.Int64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Repeated(pc.PathValueRepeated, `uint32_repeated`, &req.Uint32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Repeated(pc.PathValueRepeated, `uint64_repeated`, &req.Uint64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatRepeated(pc.PathValueRepeated, `float_repeated`, &req.FloatRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleRepeated(pc.PathValueRepeated, `double_repeated`, &req.DoubleRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringRepeated(pc.PathValueRepeated, `string_repeated`, &req.StringRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesRepeated(pc.PathValueRepeated, `bytes_repeated`, &req.BytesRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumRepeated(pc.PathValueRepeated, `genre_repeated`, &req.GenreRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameRepeated(pc.PathValueRepeated, `genre_name_repeated`, &req.GenreNameRepeated, Genre_value, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolMap(pc.PathValueMap, `bool_map`, &req.BoolMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Map(pc.PathValueMap, `int32_map`, &req.Int32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Map(pc.PathValueMap, `int64_map`, &req.Int64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Map(pc.PathValueMap, `uint32_map`, &req.Uint32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Map(pc.PathValueMap, `uint64_map`, &req.Uint64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatMap(pc.PathValueMap, `float_map`, &req.FloatMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleMap(pc.PathValueMap, `double_map`, &req.DoubleMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringMap(pc.PathValueMap, `string_map`, &req.StringMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesMap(pc.PathValueMap, `bytes_map`, &req.BytesMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumMap(pc.PathValueMap, `genre_map`, &req.GenreMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameMap(pc.PathValueMap, `genre_name_map`, &req.GenreNameMap, Genre_value, false); err != nil {
				return nil, err
			}
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				rsp, err = set.Service.Impl.(ParamsServer).Path(ctx, req)
			}
			return protoapi.AfterAspect(set, idx, ctx, req, rsp, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBlBhcmFtcxoFcXVlcnkyPwoR6K+75Y+WcXVlcnnlj4LmlbASFumAmui/h3BhdGjkvKDpgJLlj4LmlbAqDS9wYXJhbXMvcXVlcnloAnDIAUoGCgRib29sSgcKBWludDMySgcKBWludDY0SggKBnVpbnQzMkoICgZ1aW50NjRKBwoFZmxvYXRKCAoGZG91YmxlSggKBnN0cmluZ0oHCgVieXRlc0oHCgVnZW5yZUoMCgpnZW5yZV9uYW1lSg8KDWJvb2xfb3B0aW9uYWxKEAoOaW50MzJfb3B0aW9uYWxKEAoOaW50NjRfb3B0aW9uYWxKEQoPdWludDMyX29wdGlvbmFsShEKD3VpbnQ2NF9vcHRpb25hbEoQCg5mbG9hdF9vcHRpb25hbEoRCg9kb3VibGVfb3B0aW9uYWxKEQoPc3RyaW5nX29wdGlvbmFsShAKDmJ5dGVzX29wdGlvbmFsShAKDmdlbnJlX29wdGlvbmFsShUKE2dlbnJlX25hbWVfb3B0aW9uYWxKDwoNYm9vbF9yZXBlYXRlZEoQCg5pbnQzMl9yZXBlYXRlZEoQCg5pbnQ2NF9yZXBlYXRlZEoRCg91aW50MzJfcmVwZWF0ZWRKEQoPdWludDY0X3JlcGVhdGVkShAKDmZsb2F0X3JlcGVhdGVkShEKD2RvdWJsZV9yZXBlYXRlZEoRCg9zdHJpbmdfcmVwZWF0ZWRKEAoOYnl0ZXNfcmVwZWF0ZWRKEAoOZ2VucmVfcmVwZWF0ZWRKFQoTZ2VucmVfbmFtZV9yZXBlYXRlZEoKCghib29sX21hcEoLCglpbnQzMl9tYXBKCwoJaW50NjRfbWFwSgwKCnVpbnQzMl9tYXBKDAoKdWludDY0X21hcEoLCglmbG9hdF9tYXBKDAoKZG91YmxlX21hcEoMCgpzdHJpbmdfbWFwSgsKCWJ5dGVzX21hcEoLCglnZW5yZV9tYXBKEAoOZ2VucmVfbmFtZV9tYXA=`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(ParamsInQuery)
			if err = protoapi.ParamBool(pc.QueryValue, `bool`, &req.Bool); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32(pc.QueryValue, `int32`, &req.Int32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64(pc.QueryValue, `int64`, &req.Int64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32(pc.QueryValue, `uint32`, &req.Uint32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64(pc.QueryValue, `uint64`, &req.Uint64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloat(pc.QueryValue, `float`, &req.Float); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDouble(pc.QueryValue, `double`, &req.Double); err != nil {
				return nil, err
			}
			if err = protoapi.ParamString(pc.QueryValue, `string`, &req.String_); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytes(pc.QueryValue, `bytes`, &req.Bytes); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnum(pc.QueryValue, `genre`, &req.Genre); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumName(pc.QueryValue, `genre_name`, &req.GenreName, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolOptional(pc.QueryValue, `bool_optional`, &req.BoolOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Optional(pc.QueryValue, `int32_optional`, &req.Int32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Optional(pc.QueryValue, `int64_optional`, &req.Int64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Optional(pc.QueryValue, `uint32_optional`, &req.Uint32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Optional(pc.QueryValue, `uint64_optional`, &req.Uint64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatOptional(pc.QueryValue, `float_optional`, &req.FloatOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleOptional(pc.QueryValue, `double_optional`, &req.DoubleOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringOptional(pc.QueryValue, `string_optional`, &req.StringOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesOptional(pc.QueryValue, `bytes_optional`, &req.BytesOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumOptional(pc.QueryValue, `genre_optional`, &req.GenreOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameOptional(pc.QueryValue, `genre_name_optional`, &req.GenreNameOptional, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolRepeated(pc.QueryValueRepeated, `bool_repeated`, &req.BoolRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Repeated(pc.QueryValueRepeated, `int32_repeated`, &req.Int32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Repeated(pc.QueryValueRepeated, `int64_repeated`, &req.Int64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Repeated(pc.QueryValueRepeated, `uint32_repeated`, &req.Uint32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Repeated(pc.QueryValueRepeated, `uint64_repeated`, &req.Uint64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatRepeated(pc.QueryValueRepeated, `float_repeated`, &req.FloatRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleRepeated(pc.QueryValueRepeated, `double_repeated`, &req.DoubleRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringRepeated(pc.QueryValueRepeated, `string_repeated`, &req.StringRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesRepeated(pc.QueryValueRepeated, `bytes_repeated`, &req.BytesRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumRepeated(pc.QueryValueRepeated, `genre_repeated`, &req.GenreRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameRepeated(pc.QueryValueRepeated, `genre_name_repeated`, &req.GenreNameRepeated, Genre_value, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolMap(pc.QueryValueMap, `bool_map`, &req.BoolMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Map(pc.QueryValueMap, `int32_map`, &req.Int32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Map(pc.QueryValueMap, `int64_map`, &req.Int64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Map(pc.QueryValueMap, `uint32_map`, &req.Uint32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Map(pc.QueryValueMap, `uint64_map`, &req.Uint64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatMap(pc.QueryValueMap, `float_map`, &req.FloatMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleMap(pc.QueryValueMap, `double_map`, &req.DoubleMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringMap(pc.QueryValueMap, `string_map`, &req.StringMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesMap(pc.QueryValueMap, `bytes_map`, &req.BytesMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumMap(pc.QueryValueMap, `genre_map`, &req.GenreMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameMap(pc.QueryValueMap, `genre_name_map`, &req.GenreNameMap, Genre_value, false); err != nil {
				return nil, err
			}
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				rsp, err = set.Service.Impl.(ParamsServer).Query(ctx, req)
			}
			return protoapi.AfterAspect(set, idx, ctx, req, rsp, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBlBhcmFtcxoGaGVhZGVyMkMKEuivu+WPlmhlYWRlcuWPguaVsBIY6YCa6L+HaGVhZGVy5Lyg6YCS5Y+C5pWwKg4vcGFyYW1zL2hlYWRlcmgCcMgBSgYKBGJvb2xKBwoFaW50MzJKBwoFaW50NjRKCAoGdWludDMySggKBnVpbnQ2NEoHCgVmbG9hdEoICgZkb3VibGVKCAoGc3RyaW5nSgcKBWJ5dGVzSgcKBWdlbnJlSgwKCmdlbnJlX25hbWVKDwoNYm9vbF9vcHRpb25hbEoQCg5pbnQzMl9vcHRpb25hbEoQCg5pbnQ2NF9vcHRpb25hbEoRCg91aW50MzJfb3B0aW9uYWxKEQoPdWludDY0X29wdGlvbmFsShAKDmZsb2F0X29wdGlvbmFsShEKD2RvdWJsZV9vcHRpb25hbEoRCg9zdHJpbmdfb3B0aW9uYWxKEAoOYnl0ZXNfb3B0aW9uYWxKEAoOZ2VucmVfb3B0aW9uYWxKFQoTZ2VucmVfbmFtZV9vcHRpb25hbEoPCg1ib29sX3JlcGVhdGVkShAKDmludDMyX3JlcGVhdGVkShAKDmludDY0X3JlcGVhdGVkShEKD3VpbnQzMl9yZXBlYXRlZEoRCg91aW50NjRfcmVwZWF0ZWRKEAoOZmxvYXRfcmVwZWF0ZWRKEQoPZG91YmxlX3JlcGVhdGVkShEKD3N0cmluZ19yZXBlYXRlZEoQCg5ieXRlc19yZXBlYXRlZEoQCg5nZW5yZV9yZXBlYXRlZEoVChNnZW5yZV9uYW1lX3JlcGVhdGVkSgoKCGJvb2xfbWFwSgsKCWludDMyX21hcEoLCglpbnQ2NF9tYXBKDAoKdWludDMyX21hcEoMCgp1aW50NjRfbWFwSgsKCWZsb2F0X21hcEoMCgpkb3VibGVfbWFwSgwKCnN0cmluZ19tYXBKCwoJYnl0ZXNfbWFwSgsKCWdlbnJlX21hcEoQCg5nZW5yZV9uYW1lX21hcA==`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(ParamsInHeader)
			if err = protoapi.ParamBool(pc.HeaderValue, `bool`, &req.Bool); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32(pc.HeaderValue, `int32`, &req.Int32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64(pc.HeaderValue, `int64`, &req.Int64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32(pc.HeaderValue, `uint32`, &req.Uint32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64(pc.HeaderValue, `uint64`, &req.Uint64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloat(pc.HeaderValue, `float`, &req.Float); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDouble(pc.HeaderValue, `double`, &req.Double); err != nil {
				return nil, err
			}
			if err = protoapi.ParamString(pc.HeaderValue, `string`, &req.String_); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytes(pc.HeaderValue, `bytes`, &req.Bytes); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnum(pc.HeaderValue, `genre`, &req.Genre); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumName(pc.HeaderValue, `genre_name`, &req.GenreName, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolOptional(pc.HeaderValue, `bool_optional`, &req.BoolOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Optional(pc.HeaderValue, `int32_optional`, &req.Int32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Optional(pc.HeaderValue, `int64_optional`, &req.Int64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Optional(pc.HeaderValue, `uint32_optional`, &req.Uint32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Optional(pc.HeaderValue, `uint64_optional`, &req.Uint64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatOptional(pc.HeaderValue, `float_optional`, &req.FloatOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleOptional(pc.HeaderValue, `double_optional`, &req.DoubleOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringOptional(pc.HeaderValue, `string_optional`, &req.StringOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesOptional(pc.HeaderValue, `bytes_optional`, &req.BytesOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumOptional(pc.HeaderValue, `genre_optional`, &req.GenreOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameOptional(pc.HeaderValue, `genre_name_optional`, &req.GenreNameOptional, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolRepeated(pc.HeaderValueRepeated, `bool_repeated`, &req.BoolRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Repeated(pc.HeaderValueRepeated, `int32_repeated`, &req.Int32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Repeated(pc.HeaderValueRepeated, `int64_repeated`, &req.Int64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Repeated(pc.HeaderValueRepeated, `uint32_repeated`, &req.Uint32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Repeated(pc.HeaderValueRepeated, `uint64_repeated`, &req.Uint64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatRepeated(pc.HeaderValueRepeated, `float_repeated`, &req.FloatRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleRepeated(pc.HeaderValueRepeated, `double_repeated`, &req.DoubleRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringRepeated(pc.HeaderValueRepeated, `string_repeated`, &req.StringRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesRepeated(pc.HeaderValueRepeated, `bytes_repeated`, &req.BytesRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumRepeated(pc.HeaderValueRepeated, `genre_repeated`, &req.GenreRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameRepeated(pc.HeaderValueRepeated, `genre_name_repeated`, &req.GenreNameRepeated, Genre_value, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolMap(pc.HeaderValueMap, `bool_map`, &req.BoolMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Map(pc.HeaderValueMap, `int32_map`, &req.Int32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Map(pc.HeaderValueMap, `int64_map`, &req.Int64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Map(pc.HeaderValueMap, `uint32_map`, &req.Uint32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Map(pc.HeaderValueMap, `uint64_map`, &req.Uint64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatMap(pc.HeaderValueMap, `float_map`, &req.FloatMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleMap(pc.HeaderValueMap, `double_map`, &req.DoubleMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringMap(pc.HeaderValueMap, `string_map`, &req.StringMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesMap(pc.HeaderValueMap, `bytes_map`, &req.BytesMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumMap(pc.HeaderValueMap, `genre_map`, &req.GenreMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameMap(pc.HeaderValueMap, `genre_name_map`, &req.GenreNameMap, Genre_value, false); err != nil {
				return nil, err
			}
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				rsp, err = set.Service.Impl.(ParamsServer).Header(ctx, req)
			}
			return protoapi.AfterAspect(set, idx, ctx, req, rsp, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBlBhcmFtcxoGY29va2llMkMKEuivu+WPlmNvb2tpZeWPguaVsBIY6YCa6L+HY29va2ll5Lyg6YCS5Y+C5pWwKg4vcGFyYW1zL2Nvb2tpZWgCcMgBSgYKBGJvb2xKBwoFaW50MzJKBwoFaW50NjRKCAoGdWludDMySggKBnVpbnQ2NEoHCgVmbG9hdEoICgZkb3VibGVKCAoGc3RyaW5nSgcKBWJ5dGVzSgcKBWdlbnJlSgwKCmdlbnJlX25hbWVKDwoNYm9vbF9vcHRpb25hbEoQCg5pbnQzMl9vcHRpb25hbEoQCg5pbnQ2NF9vcHRpb25hbEoRCg91aW50MzJfb3B0aW9uYWxKEQoPdWludDY0X29wdGlvbmFsShAKDmZsb2F0X29wdGlvbmFsShEKD2RvdWJsZV9vcHRpb25hbEoRCg9zdHJpbmdfb3B0aW9uYWxKEAoOYnl0ZXNfb3B0aW9uYWxKEAoOZ2VucmVfb3B0aW9uYWxKFQoTZ2VucmVfbmFtZV9vcHRpb25hbEoPCg1ib29sX3JlcGVhdGVkShAKDmludDMyX3JlcGVhdGVkShAKDmludDY0X3JlcGVhdGVkShEKD3VpbnQzMl9yZXBlYXRlZEoRCg91aW50NjRfcmVwZWF0ZWRKEAoOZmxvYXRfcmVwZWF0ZWRKEQoPZG91YmxlX3JlcGVhdGVkShEKD3N0cmluZ19yZXBlYXRlZEoQCg5ieXRlc19yZXBlYXRlZEoQCg5nZW5yZV9yZXBlYXRlZEoVChNnZW5yZV9uYW1lX3JlcGVhdGVkSgoKCGJvb2xfbWFwSgsKCWludDMyX21hcEoLCglpbnQ2NF9tYXBKDAoKdWludDMyX21hcEoMCgp1aW50NjRfbWFwSgsKCWZsb2F0X21hcEoMCgpkb3VibGVfbWFwSgwKCnN0cmluZ19tYXBKCwoJYnl0ZXNfbWFwSgsKCWdlbnJlX21hcEoQCg5nZW5yZV9uYW1lX21hcA==`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(ParamsInCookie)
			if err = protoapi.ParamBool(pc.CookieValue, `bool`, &req.Bool); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32(pc.CookieValue, `int32`, &req.Int32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64(pc.CookieValue, `int64`, &req.Int64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32(pc.CookieValue, `uint32`, &req.Uint32); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64(pc.CookieValue, `uint64`, &req.Uint64); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloat(pc.CookieValue, `float`, &req.Float); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDouble(pc.CookieValue, `double`, &req.Double); err != nil {
				return nil, err
			}
			if err = protoapi.ParamString(pc.CookieValue, `string`, &req.String_); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytes(pc.CookieValue, `bytes`, &req.Bytes); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnum(pc.CookieValue, `genre`, &req.Genre); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumName(pc.CookieValue, `genre_name`, &req.GenreName, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolOptional(pc.CookieValue, `bool_optional`, &req.BoolOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Optional(pc.CookieValue, `int32_optional`, &req.Int32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Optional(pc.CookieValue, `int64_optional`, &req.Int64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Optional(pc.CookieValue, `uint32_optional`, &req.Uint32Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Optional(pc.CookieValue, `uint64_optional`, &req.Uint64Optional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatOptional(pc.CookieValue, `float_optional`, &req.FloatOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleOptional(pc.CookieValue, `double_optional`, &req.DoubleOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringOptional(pc.CookieValue, `string_optional`, &req.StringOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesOptional(pc.CookieValue, `bytes_optional`, &req.BytesOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumOptional(pc.CookieValue, `genre_optional`, &req.GenreOptional); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameOptional(pc.CookieValue, `genre_name_optional`, &req.GenreNameOptional, Genre_value); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolRepeated(pc.CookieValueRepeated, `bool_repeated`, &req.BoolRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Repeated(pc.CookieValueRepeated, `int32_repeated`, &req.Int32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Repeated(pc.CookieValueRepeated, `int64_repeated`, &req.Int64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Repeated(pc.CookieValueRepeated, `uint32_repeated`, &req.Uint32Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Repeated(pc.CookieValueRepeated, `uint64_repeated`, &req.Uint64Repeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatRepeated(pc.CookieValueRepeated, `float_repeated`, &req.FloatRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleRepeated(pc.CookieValueRepeated, `double_repeated`, &req.DoubleRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringRepeated(pc.CookieValueRepeated, `string_repeated`, &req.StringRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesRepeated(pc.CookieValueRepeated, `bytes_repeated`, &req.BytesRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumRepeated(pc.CookieValueRepeated, `genre_repeated`, &req.GenreRepeated, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameRepeated(pc.CookieValueRepeated, `genre_name_repeated`, &req.GenreNameRepeated, Genre_value, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBoolMap(pc.CookieValueMap, `bool_map`, &req.BoolMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt32Map(pc.CookieValueMap, `int32_map`, &req.Int32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamInt64Map(pc.CookieValueMap, `int64_map`, &req.Int64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint32Map(pc.CookieValueMap, `uint32_map`, &req.Uint32Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamUint64Map(pc.CookieValueMap, `uint64_map`, &req.Uint64Map, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamFloatMap(pc.CookieValueMap, `float_map`, &req.FloatMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamDoubleMap(pc.CookieValueMap, `double_map`, &req.DoubleMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamStringMap(pc.CookieValueMap, `string_map`, &req.StringMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamBytesMap(pc.CookieValueMap, `bytes_map`, &req.BytesMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumMap(pc.CookieValueMap, `genre_map`, &req.GenreMap, false); err != nil {
				return nil, err
			}
			if err = protoapi.ParamEnumNameMap(pc.CookieValueMap, `genre_name_map`, &req.GenreNameMap, Genre_value, false); err != nil {
				return nil, err
			}
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				rsp, err = set.Service.Impl.(ParamsServer).Cookie(ctx, req)
			}
			return protoapi.AfterAspect(set, idx, ctx, req, rsp, err)
		},
	})
	return ret
}
