// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: store.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Store_Simple_FullMethodName        = "/api.Store/Simple"
	Store_Client_FullMethodName        = "/api.Store/Client"
	Store_Server_FullMethodName        = "/api.Store/Server"
	Store_Bidirectional_FullMethodName = "/api.Store/Bidirectional"
	Store_UploadCovert_FullMethodName  = "/api.Store/UploadCovert"
	Store_ReviewCovert_FullMethodName  = "/api.Store/ReviewCovert"
)

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreClient interface {
	Simple(ctx context.Context, in *Book, opts ...grpc.CallOption) (*Book, error)
	Client(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Book, Book], error)
	Server(ctx context.Context, in *Book, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Book], error)
	Bidirectional(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Book, Book], error)
	UploadCovert(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
	ReviewCovert(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
}

type storeClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreClient(cc grpc.ClientConnInterface) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Simple(ctx context.Context, in *Book, opts ...grpc.CallOption) (*Book, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Book)
	err := c.cc.Invoke(ctx, Store_Simple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Client(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Book, Book], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Store_ServiceDesc.Streams[0], Store_Client_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Book, Book]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_ClientClient = grpc.ClientStreamingClient[Book, Book]

func (c *storeClient) Server(ctx context.Context, in *Book, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Book], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Store_ServiceDesc.Streams[1], Store_Server_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Book, Book]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_ServerClient = grpc.ServerStreamingClient[Book]

func (c *storeClient) Bidirectional(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Book, Book], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Store_ServiceDesc.Streams[2], Store_Bidirectional_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Book, Book]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_BidirectionalClient = grpc.BidiStreamingClient[Book, Book]

func (c *storeClient) UploadCovert(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, Store_UploadCovert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) ReviewCovert(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, Store_ReviewCovert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
// All implementations should embed UnimplementedStoreServer
// for forward compatibility.
type StoreServer interface {
	Simple(context.Context, *Book) (*Book, error)
	Client(grpc.ClientStreamingServer[Book, Book]) error
	Server(*Book, grpc.ServerStreamingServer[Book]) error
	Bidirectional(grpc.BidiStreamingServer[Book, Book]) error
	UploadCovert(context.Context, *Void) (*Void, error)
	ReviewCovert(context.Context, *Void) (*Void, error)
}

// UnimplementedStoreServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServer struct{}

func (UnimplementedStoreServer) Simple(context.Context, *Book) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simple not implemented")
}
func (UnimplementedStoreServer) Client(grpc.ClientStreamingServer[Book, Book]) error {
	return status.Errorf(codes.Unimplemented, "method Client not implemented")
}
func (UnimplementedStoreServer) Server(*Book, grpc.ServerStreamingServer[Book]) error {
	return status.Errorf(codes.Unimplemented, "method Server not implemented")
}
func (UnimplementedStoreServer) Bidirectional(grpc.BidiStreamingServer[Book, Book]) error {
	return status.Errorf(codes.Unimplemented, "method Bidirectional not implemented")
}
func (UnimplementedStoreServer) UploadCovert(context.Context, *Void) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadCovert not implemented")
}
func (UnimplementedStoreServer) ReviewCovert(context.Context, *Void) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewCovert not implemented")
}
func (UnimplementedStoreServer) testEmbeddedByValue() {}

// UnsafeStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServer will
// result in compilation errors.
type UnsafeStoreServer interface {
	mustEmbedUnimplementedStoreServer()
}

func RegisterStoreServer(s grpc.ServiceRegistrar, srv StoreServer) {
	// If the following call pancis, it indicates UnimplementedStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Store_ServiceDesc, srv)
}

func _Store_Simple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Book)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_Simple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Simple(ctx, req.(*Book))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Client_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServer).Client(&grpc.GenericServerStream[Book, Book]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_ClientServer = grpc.ClientStreamingServer[Book, Book]

func _Store_Server_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Book)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServer).Server(m, &grpc.GenericServerStream[Book, Book]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_ServerServer = grpc.ServerStreamingServer[Book]

func _Store_Bidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServer).Bidirectional(&grpc.GenericServerStream[Book, Book]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_BidirectionalServer = grpc.BidiStreamingServer[Book, Book]

func _Store_UploadCovert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).UploadCovert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_UploadCovert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).UploadCovert(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_ReviewCovert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).ReviewCovert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_ReviewCovert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).ReviewCovert(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// Store_ServiceDesc is the grpc.ServiceDesc for Store service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Store_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simple",
			Handler:    _Store_Simple_Handler,
		},
		{
			MethodName: "UploadCovert",
			Handler:    _Store_UploadCovert_Handler,
		},
		{
			MethodName: "ReviewCovert",
			Handler:    _Store_ReviewCovert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Client",
			Handler:       _Store_Client_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Server",
			Handler:       _Store_Server_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Bidirectional",
			Handler:       _Store_Bidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "store.proto",
}
