// Code generated by protoc-gen-go-protoapi. DO NOT EDIT!
// versions:
// - protoc-gen-go-protoapi v1.0.0
// - protoc                 v3.21.12
// source: store.proto
// create: 2025-03-21 16:47:25

package api

import (
	"context"
	"github.com/hezof/protoapi"
	"github.com/hezof/protojson"
	"io"
)

func (x *Book) DecodeField(r *protojson.JsonDecoder, f string) {
	switch f {
	case `sale`:
		protojson.DecodeBool(r, &x.Sale)
	case `stars`:
		protojson.DecodeInt32(r, &x.Stars)
	case `ptime`:
		protojson.DecodeInt64(r, &x.Publication)
	case `pages`:
		protojson.DecodeUint32(r, &x.Pages)
	case `stock`:
		protojson.DecodeUint64(r, &x.Stock)
	case `price`:
		protojson.DecodeFloat(r, &x.Price)
	case `discount`:
		protojson.DecodeDouble(r, &x.Discount)
	case `name`:
		protojson.DecodeString(r, &x.Name)
	case `cover`:
		protojson.DecodeBytes(r, &x.Cover)
	case `genre`:
		protojson.DecodeEnum(r, &x.Genre)
	case `genre_name`:
		protojson.DecodeEnum(r, &x.GenreName)
	case `author`:
		protojson.DecodeMessage(r, &x.Author)
	case `isbn`:
		protojson.DecodeString(r, &x.Isbn)
	}
}
func (x *Book) EncodeField(w *protojson.JsonEncoder) {
	protojson.EncodeBool_WithEmpty(w, `sale`, x.Sale)
	protojson.EncodeInt32_OmitEmpty(w, `stars`, x.Stars)
	protojson.EncodeInt64_OmitEmpty(w, `ptime`, x.Publication)
	protojson.EncodeUint32_OmitEmpty(w, `pages`, x.Pages)
	protojson.EncodeUint64_OmitEmpty(w, `stock`, x.Stock)
	protojson.EncodeFloat_WithEmpty(w, `price`, x.Price)
	protojson.EncodeDouble_OmitEmpty(w, `discount`, x.Discount)
	protojson.EncodeString_OmitEmpty(w, `name`, x.Name)
	protojson.EncodeBytes_OmitEmpty(w, `cover`, x.Cover)
	protojson.EncodeEnum_OmitEmpty(w, `genre`, x.Genre)
	protojson.EncodeEnum_OmitEmpty(w, `genre_name`, x.GenreName)
	protojson.EncodeMessage_ConvEmpty(w, `author`, x.Author)
	protojson.EncodeString_OmitEmpty(w, `isbn`, x.Isbn)
}
func (x *Book) Validate(set *protoapi.MethodSetting, ctx context.Context) error {
	if err := set.MessageExtend(ctx, x); err != nil {
		return err
	}
	if err := set.FieldPlugins[0](ctx, `sale`, x.Sale, set.Meta.FieldRules[0].Plugin); err != nil {
		return err
	}
	if x.Stars < 1 {
		return set.Meta.FieldRules[1].Minimum.Err
	}
	if x.Stars > 5 {
		return set.Meta.FieldRules[1].Maximum.Err
	}
	if x.Publication < 946656000 {
		return set.Meta.FieldRules[2].Minimum.Err
	}
	if x.Publication > 4102416000 {
		return set.Meta.FieldRules[2].Maximum.Err
	}
	if x.Price < 1 {
		return set.Meta.FieldRules[5].Minimum.Err
	}
	if x.Name == `` {
		return set.Meta.FieldRules[7].Required
	}
	if x.Cover != nil {
		if len(x.Cover) < 1 {
			return set.Meta.FieldRules[8].MinLength.Err
		}
	}
	if x.Cover != nil {
		if len(x.Cover) > 10240 {
			return set.Meta.FieldRules[8].MaxLength.Err
		}
	}
	return nil
}
func (x *Author) DecodeField(r *protojson.JsonDecoder, f string) {
	switch f {
	case `no`:
		protojson.DecodeUint64(r, &x.No)
	case `name`:
		protojson.DecodeString(r, &x.Name)
	case `email`:
		protojson.DecodeString(r, &x.Email)
	}
}
func (x *Author) EncodeField(w *protojson.JsonEncoder) {
	protojson.EncodeUint64_OmitEmpty(w, `no`, x.No)
	protojson.EncodeString_OmitEmpty(w, `name`, x.Name)
	protojson.EncodeString_OmitEmpty(w, `email`, x.Email)
}
func (x *Void) DecodeField(r *protojson.JsonDecoder, f string) {
	switch f {
	}
}
func (x *Void) EncodeField(w *protojson.JsonEncoder) {
}
func StoreRegistry(impl interface{}, aspects []protoapi.ServiceAspect) *protoapi.ServiceSetting {
	ret := new(protoapi.ServiceSetting)
	ret.Impl = impl
	ret.Desc = &Store_ServiceDesc
	ret.HttpOnly = false
	ret.Aspects = aspects
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBVN0b3JlGgZTaW1wbGUyhAEKDOWIm+W7uuS5puexjRIt6YCa6L+H6K+l5pa55rOV5Y+v5Lul5Yib5bu65LiA5pys5Lmm57GN5L+h5oGvKgwvc2ltcGxlL2Jvb2twyAGCARgIkwMQoZwBIg/kuabnsY3lt7LlrZjlnKiCARgI9gMQopwBIg/mnI3liqHnq6/plJnor686GwiRThIFYWRtaW4aD+i2hee6p+euoeeQhuWRmEINbWVzc2FnZShCb29rKUo4CgRzYWxlWjAKEGNoZWNrX3NhbGUoYm9vaykSHAiTAxCqjQYiE+S/g+mUgOWPguaVsOmUmeivryFKSwoFc3RhcnMaIAgBEhwIkwMQq40GIhPngrnotZ7mmJ/mlbDplJnor68hIiAIBRIcCJMDEKyNBiIT54K56LWe5pif5pWw6ZSZ6K+vIUpTCgVwdGltZRokCICms8MDEhwIkwMQrY0GIhPlh7rniYjml7bpl7TplJnor68hIiQIgM2XpA8SHAiTAxCujQYiE+WHuueJiOaXtumXtOmUmeivryFKBwoFcGFnZXNKBwoFc3RvY2tKRQoFcHJpY2USGwiTAxCwjQYiEuS5puexjeS7t+agvOmUmeivrxofCAESGwiTAxCxjQYiEuS5puexjeS7t+agvOmUmeivr0oKCghkaXNjb3VudEojCgRuYW1lEhsIkwMQso0GIhLkuabnsY3lkI3np7DplJnor69KUAoFY292ZXIqIQgBEh0IkwMQro0GIhTlsIHpnaLmlbDmja7mnIDlsI8xYjIkCIBQEh8IkwMQr40GIhblsIHpnaLmlbDmja7mnIDlpKcxMEtiSgcKBWdlbnJlSgwKCmdlbnJlX25hbWVKCAoGYXV0aG9ySgYKBGlzYm4=`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(Book)
			if err = protoapi.DecodeRequest(in, req); err != nil {
				return nil, err
			}
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				rsp, err = set.Service.Impl.(StoreServer).Simple(ctx, req)
			}
			return protoapi.AfterAspect(set, idx, ctx, req, rsp, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBVN0b3JlGgZDbGllbnQgATJ2ChjmtYHlvI/mibnph4/liJvlu7rkuabnsY0SOemAmui/h+ivpeaWueazleWPr+S7pea1geW8j+aJuemHj+WIm+W7uuWkmuacrOS5puexjeS/oeaBryoML2NsaWVudC9ib29rYgwvY2xpZW50L2Jvb2twyAF4AUINbWVzc2FnZShCb29rKUo4CgRzYWxlWjAKEGNoZWNrX3NhbGUoYm9vaykSHAiTAxCqjQYiE+S/g+mUgOWPguaVsOmUmeivryFKSwoFc3RhcnMaIAgBEhwIkwMQq40GIhPngrnotZ7mmJ/mlbDplJnor68hIiAIBRIcCJMDEKyNBiIT54K56LWe5pif5pWw6ZSZ6K+vIUpTCgVwdGltZRokCICms8MDEhwIkwMQrY0GIhPlh7rniYjml7bpl7TplJnor68hIiQIgM2XpA8SHAiTAxCujQYiE+WHuueJiOaXtumXtOmUmeivryFKBwoFcGFnZXNKBwoFc3RvY2tKRQoFcHJpY2USGwiTAxCwjQYiEuS5puexjeS7t+agvOmUmeivrxofCAESGwiTAxCxjQYiEuS5puexjeS7t+agvOmUmeivr0oKCghkaXNjb3VudEojCgRuYW1lEhsIkwMQso0GIhLkuabnsY3lkI3np7DplJnor69KUAoFY292ZXIqIQgBEh0IkwMQro0GIhTlsIHpnaLmlbDmja7mnIDlsI8xYjIkCIBQEh8IkwMQr40GIhblsIHpnaLmlbDmja7mnIDlpKcxMEtiSgcKBWdlbnJlSgwKCmdlbnJlX25hbWVKCAoGYXV0aG9ySgYKBGlzYm4=`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			idx, ctx, err := protoapi.BeforeAspect(set, pc, nil)
			if err == nil {
				err = set.Service.Impl.(StoreServer).Client(protoapi.StreamServer[Book, Book](pc))
			}
			return protoapi.AfterAspect(set, idx, ctx, nil, nil, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBVN0b3JlGgZTZXJ2ZXIoATJzCh7mtYHlvI/ov5Tlm57mibnph4/kuabnsY3kv6Hmga8SMOmAmui/h+ivpeaWueazleWPr+S7pea1geW8j+i/lOWbnuaMh+S5puexjeS/oeaBryoML3NlcnZlci9ib29rYgwvc2VydmVyL2Jvb2twyAF4AUINbWVzc2FnZShCb29rKUo4CgRzYWxlWjAKEGNoZWNrX3NhbGUoYm9vaykSHAiTAxCqjQYiE+S/g+mUgOWPguaVsOmUmeivryFKSwoFc3RhcnMaIAgBEhwIkwMQq40GIhPngrnotZ7mmJ/mlbDplJnor68hIiAIBRIcCJMDEKyNBiIT54K56LWe5pif5pWw6ZSZ6K+vIUpTCgVwdGltZRokCICms8MDEhwIkwMQrY0GIhPlh7rniYjml7bpl7TplJnor68hIiQIgM2XpA8SHAiTAxCujQYiE+WHuueJiOaXtumXtOmUmeivryFKBwoFcGFnZXNKBwoFc3RvY2tKRQoFcHJpY2USGwiTAxCwjQYiEuS5puexjeS7t+agvOmUmeivrxofCAESGwiTAxCxjQYiEuS5puexjeS7t+agvOmUmeivr0oKCghkaXNjb3VudEojCgRuYW1lEhsIkwMQso0GIhLkuabnsY3lkI3np7DplJnor69KUAoFY292ZXIqIQgBEh0IkwMQro0GIhTlsIHpnaLmlbDmja7mnIDlsI8xYjIkCIBQEh8IkwMQr40GIhblsIHpnaLmlbDmja7mnIDlpKcxMEtiSgcKBWdlbnJlSgwKCmdlbnJlX25hbWVKCAoGYXV0aG9ySgYKBGlzYm4=`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(Book)
			if err = protoapi.DecodeRequest(in, req); err != nil {
				return nil, err
			}
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				err = set.Service.Impl.(StoreServer).Server(req, protoapi.StreamServer[Book, Book](pc))
			}
			return protoapi.AfterAspect(set, idx, ctx, req, nil, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBVN0b3JlGg1CaWRpcmVjdGlvbmFsIAEoATKBAQoe5rWB5byP6L+U5Zue5om56YeP5Lmm57GN5L+h5oGvEjDpgJrov4for6Xmlrnms5Xlj6/ku6XmtYHlvI/ov5Tlm57mjIfkuabnsY3kv6Hmga8qEy9iaWRpcmVjdGlvbmFsL2Jvb2tiEy9iaWRpcmVjdGlvbmFsL2Jvb2twyAF4AUINbWVzc2FnZShCb29rKUo4CgRzYWxlWjAKEGNoZWNrX3NhbGUoYm9vaykSHAiTAxCqjQYiE+S/g+mUgOWPguaVsOmUmeivryFKSwoFc3RhcnMaIAgBEhwIkwMQq40GIhPngrnotZ7mmJ/mlbDplJnor68hIiAIBRIcCJMDEKyNBiIT54K56LWe5pif5pWw6ZSZ6K+vIUpTCgVwdGltZRokCICms8MDEhwIkwMQrY0GIhPlh7rniYjml7bpl7TplJnor68hIiQIgM2XpA8SHAiTAxCujQYiE+WHuueJiOaXtumXtOmUmeivryFKBwoFcGFnZXNKBwoFc3RvY2tKRQoFcHJpY2USGwiTAxCwjQYiEuS5puexjeS7t+agvOmUmeivrxofCAESGwiTAxCxjQYiEuS5puexjeS7t+agvOmUmeivr0oKCghkaXNjb3VudEojCgRuYW1lEhsIkwMQso0GIhLkuabnsY3lkI3np7DplJnor69KUAoFY292ZXIqIQgBEh0IkwMQro0GIhTlsIHpnaLmlbDmja7mnIDlsI8xYjIkCIBQEh8IkwMQr40GIhblsIHpnaLmlbDmja7mnIDlpKcxMEtiSgcKBWdlbnJlSgwKCmdlbnJlX25hbWVKCAoGYXV0aG9ySgYKBGlzYm4=`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			idx, ctx, err := protoapi.BeforeAspect(set, pc, nil)
			if err == nil {
				err = set.Service.Impl.(StoreServer).Bidirectional(protoapi.StreamServer[Book, Book](pc))
			}
			return protoapi.AfterAspect(set, idx, ctx, nil, nil, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBVN0b3JlGgxVcGxvYWRDb3ZlcnQyTAoS5LiK5Lyg5bCB6Z2i5Zu+54mHEiHpgJrov4for6Xmlrnms5XkuIrkvKDlsIHpnaLlm77niYcqDi9jb3ZlcnQvdXBsb2FkaAJwyQE=`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(Void)
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				rsp, err = set.Service.Impl.(StoreServer).UploadCovert(ctx, req)
			}
			return protoapi.AfterAspect(set, idx, ctx, req, rsp, err)
		},
	})
	ret.Methods = append(ret.Methods, &protoapi.MethodSetting{
		Meta: protoapi.DecodeMeta(`CgNhcGkSBVN0b3JlGgxSZXZpZXdDb3ZlcnQyTAoS6aKE6KeI5bCB6Z2i5Zu+54mHEiHpgJrov4for6Xmlrnms5XpooTop4jlsIHpnaLlm77niYcaDi9yZXZpZXcvY292ZXJ0aAJwygE=`),
		Call: func(pc *protoapi.Context, in io.Reader) (rsp interface{}, err error) {
			set := pc.Handler.Setting
			req := new(Void)
			idx, ctx, err := protoapi.BeforeAspect(set, pc, req)
			if err == nil {
				rsp, err = set.Service.Impl.(StoreServer).ReviewCovert(ctx, req)
			}
			return protoapi.AfterAspect(set, idx, ctx, req, rsp, err)
		},
	})
	return ret
}
