swagger: "2.0"
tags:
- x-order: 1
  name: 商店服务
  description: 这是一个商店服务示例跨行第一句.protobuf自动拼接相邻字串!跨行第二句.protobuf自动拼接相邻字串!跨行第三句.protobuf自动拼接相邻字串!
paths:
  /simple/book:
    x-order: 1
    post:
      x-order: 1
      operationId: api.Store.Simple.POST
      summary: 创建书籍
      description: POST /simple/book<br/><br/>通过该方法可以创建一本书籍信息
      tags:
      - 商店服务
      parameters:
      - x-order: 1
        name: body
        in: body
        schema:
          x-order: 1
          $ref: '#/definitions/api.Book'
        required: true
      responses:
        "200":
          x-order: 1
          description: 请求成功
          schema:
            x-order: 2
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: "0"
              data:
                x-order: 2
                $ref: '#/definitions/api.Book'
                description: 书籍信息
        "403":
          x-order: 2
          description: 书籍已存在
          schema:
            x-order: 3
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: "20001"
              message:
                x-order: 3
                type: string
                description: 书籍已存在
        "502":
          x-order: 3
          description: 服务端错误
          schema:
            x-order: 4
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: "20002"
              message:
                x-order: 3
                type: string
                description: 服务端错误
        default:
          x-order: 4
          description: 请求错误
          schema:
            x-order: 5
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
  /client/book:
    x-order: 2
    get:
      x-order: 2
      operationId: api.Store.Client.WEBSOCKET
      summary: 流式批量创建书籍
      description: WEBSOCKET /client/book<br/><br/>通过该方法可以流式批量创建多本书籍信息
      tags:
      - 商店服务
      parameters:
      - x-order: 2
        name: body
        in: body
        schema:
          x-order: 6
          $ref: '#/definitions/api.Book'
        required: true
      responses:
        "200":
          x-order: 5
          description: 请求成功
          schema:
            x-order: 7
            $ref: '#/definitions/api.Book'
        default:
          x-order: 6
          description: 请求错误
          schema:
            x-order: 8
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
    post:
      x-order: 2
      operationId: api.Store.Client.POST
      summary: 流式批量创建书籍
      description: POST /client/book<br/><br/>通过该方法可以流式批量创建多本书籍信息
      tags:
      - 商店服务
      parameters:
      - x-order: 2
        name: body
        in: body
        schema:
          x-order: 6
          $ref: '#/definitions/api.Book'
        required: true
      responses:
        "200":
          x-order: 5
          description: 请求成功
          schema:
            x-order: 7
            $ref: '#/definitions/api.Book'
        default:
          x-order: 6
          description: 请求错误
          schema:
            x-order: 8
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
  /server/book:
    x-order: 3
    get:
      x-order: 3
      operationId: api.Store.Server.WEBSOCKET
      summary: 流式返回批量书籍信息
      description: WEBSOCKET /server/book<br/><br/>通过该方法可以流式返回指书籍信息
      tags:
      - 商店服务
      parameters:
      - x-order: 3
        name: body
        in: body
        schema:
          x-order: 9
          $ref: '#/definitions/api.Book'
        required: true
      responses:
        "200":
          x-order: 7
          description: 请求成功
          schema:
            x-order: 10
            $ref: '#/definitions/api.Book'
        default:
          x-order: 8
          description: 请求错误
          schema:
            x-order: 11
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
    post:
      x-order: 3
      operationId: api.Store.Server.POST
      summary: 流式返回批量书籍信息
      description: POST /server/book<br/><br/>通过该方法可以流式返回指书籍信息
      tags:
      - 商店服务
      parameters:
      - x-order: 3
        name: body
        in: body
        schema:
          x-order: 9
          $ref: '#/definitions/api.Book'
        required: true
      responses:
        "200":
          x-order: 7
          description: 请求成功
          schema:
            x-order: 10
            $ref: '#/definitions/api.Book'
        default:
          x-order: 8
          description: 请求错误
          schema:
            x-order: 11
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
  /bidirectional/book:
    x-order: 4
    get:
      x-order: 4
      operationId: api.Store.Bidirectional.WEBSOCKET
      summary: 流式返回批量书籍信息
      description: WEBSOCKET /bidirectional/book<br/><br/>通过该方法可以流式返回指书籍信息
      tags:
      - 商店服务
      parameters:
      - x-order: 4
        name: body
        in: body
        schema:
          x-order: 12
          $ref: '#/definitions/api.Book'
        required: true
      responses:
        "200":
          x-order: 9
          description: 请求成功
          schema:
            x-order: 13
            $ref: '#/definitions/api.Book'
        default:
          x-order: 10
          description: 请求错误
          schema:
            x-order: 14
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
    post:
      x-order: 4
      operationId: api.Store.Bidirectional.POST
      summary: 流式返回批量书籍信息
      description: POST /bidirectional/book<br/><br/>通过该方法可以流式返回指书籍信息
      tags:
      - 商店服务
      parameters:
      - x-order: 4
        name: body
        in: body
        schema:
          x-order: 12
          $ref: '#/definitions/api.Book'
        required: true
      responses:
        "200":
          x-order: 9
          description: 请求成功
          schema:
            x-order: 13
            $ref: '#/definitions/api.Book'
        default:
          x-order: 10
          description: 请求错误
          schema:
            x-order: 14
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
  /covert/upload:
    x-order: 5
    post:
      x-order: 5
      operationId: api.Store.UploadCovert.POST
      summary: 上传封面图片
      description: POST /covert/upload<br/><br/>通过该方法上传封面图片
      tags:
      - 商店服务
      responses:
        "201":
          x-order: 11
          description: 请求成功
          schema:
            x-order: 15
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: "0"
              data:
                x-order: 2
                $ref: '#/definitions/api.Void'
                description: api.Void
        default:
          x-order: 12
          description: 请求错误
          schema:
            x-order: 16
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
  /review/covert:
    x-order: 6
    get:
      x-order: 6
      operationId: api.Store.ReviewCovert.GET
      summary: 预览封面图片
      description: GET /review/covert<br/><br/>通过该方法预览封面图片
      tags:
      - 商店服务
      responses:
        "202":
          x-order: 13
          description: 请求成功
          schema:
            x-order: 17
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: "0"
              data:
                x-order: 2
                $ref: '#/definitions/api.Void'
                description: api.Void
        default:
          x-order: 14
          description: 请求错误
          schema:
            x-order: 18
            type: object
            properties:
              code:
                x-order: 1
                type: integer
                format: int32
                description: 错误代码. 约定0表示成功, 其他表示错误.
              name:
                x-order: 2
                type: string
                description: 错误名称.可选
              message:
                x-order: 3
                type: string
                description: 错误消息.可选
      produces:
      - application/json
definitions:
  api.Book:
    x-order: 1
    type: object
    properties:
      sale:
        x-order: 19
        type: boolean
        description: 促销商品
      stars:
        x-order: 20
        type: integer
        format: int32
        maximum: 5
        minimum: 1
        description: 点赞星数
      ptime:
        x-order: 21
        type: integer
        format: int64
        maximum: 4.102416e+09
        minimum: 9.46656e+08
        description: 出版时间
      pages:
        x-order: 22
        type: integer
        format: int32
        description: 书籍页数
      stock:
        x-order: 23
        type: integer
        format: int64
        description: 书籍库存数
      price:
        x-order: 24
        type: number
        format: float
        minimum: 1
        description: 书籍价格
      discount:
        x-order: 25
        type: number
        format: double
        description: 书籍折扣
      name:
        x-order: 26
        type: string
        description: 书籍名称
      cover:
        x-order: 27
        type: string
        format: binary
        maxLength: 10240
        minLength: 1
        description: 封面数据
      genre:
        x-order: 28
        type: integer
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        description: 书籍类别(枚举数值)
      genre_name:
        x-order: 29
        type: integer
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        description: 书籍类别(枚举名称)
      author:
        x-order: 30
        $ref: '#/definitions/api.Author'
        description: 书籍作者信息
      isbn:
        x-order: 31
        type: string
        description: 书籍惟一编号
    description: 书籍信息
    required:
    - price
    - name
  api.Author:
    x-order: 2
    type: object
    properties:
      "no":
        x-order: 32
        type: integer
        format: int64
        description: 作者编号
      name:
        x-order: 33
        type: string
        description: 作者名称
      email:
        x-order: 34
        type: string
        description: 作者邮箱
    description: api.Author
  api.Void:
    x-order: 3
    type: object
    description: api.Void
