syntax = "proto3";
package api;
option go_package = ".;api";

import "github.com/hezof/protoapi.proto";

service Store {

  option (protoapi.info) = {
    name: "商店服务",
    desc: "这是一个商店服务示例"
        "跨行第一句.protobuf自动拼接相邻字串!"
        "跨行第二句.protobuf自动拼接相邻字串!"
        "跨行第三句.protobuf自动拼接相邻字串!"
  };
  option (protoapi.http_only) = false;

  rpc Simple (Book) returns(Book) {
    option (protoapi.role) = {
      code: 10001,
      name: "admin",
      desc: "超级管理员"
    };
    option (protoapi.http) = {
      name: "创建书籍",
      desc: "通过该方法可以创建一本书籍信息",
      post: "/simple/book",
      body: json,
      status: 200,
      result: normal,
      errors: [
        {
          code: 20001,
          status: 403,
          message: "书籍已存在"
        },
        {
          code: 20002,
          status: 502,
          message: "服务端错误"
        }
      ]
    };
  };

  rpc Client (stream Book) returns(Book) {
    option (protoapi.http) = {
      name: "流式批量创建书籍",
      desc: "通过该方法可以流式批量创建多本书籍信息",
      websocket: "/client/book",
      post: "/client/book",
      body: json,
      status: 200,
      result: unwrap
    };
  };

  rpc Server (Book) returns(stream Book) {
    option (protoapi.http) = {
      name: "流式返回批量书籍信息",
      desc: "通过该方法可以流式返回指书籍信息",
      websocket: "/server/book",
      post: "/server/book",
      body: json,
      status: 200,
      result: unwrap
    };
  };

  rpc Bidirectional (stream Book) returns(stream Book) {
    option (protoapi.http) = {
      name: "流式返回批量书籍信息",
      desc: "通过该方法可以流式返回指书籍信息",
      websocket: "/bidirectional/book",
      post: "/bidirectional/book",
      body: json,
      status: 200,
      result: unwrap
    };
  };


  rpc UploadCovert(Void) returns(Void) {
    option (protoapi.http) = {
      name: "上传封面图片",
      desc: "通过该方法上传封面图片",
      post: "/covert/upload",
      body: omit,
      status: 201,
      result: normal
    };
  };

  rpc ReviewCovert(Void) returns(Void) {
    option (protoapi.http) = {
      name: "预览封面图片",
      desc: "通过该方法预览封面图片",
      get: "/review/covert",
      body: omit,
      status: 202,
      result: normal
    };
  };
}

message Book {

  option (protoapi.schema) = "书籍信息";
  option (protoapi.extend) = "message(Book)"; // 扩展表达式

  bool sale = 1 [
    (protoapi.in) = body,
    (protoapi.desc) = "促销商品",
    (protoapi.zero) = with_empty,
    (protoapi.plugin) = {
      val: "check_sale(book)",
      err: {
        code: 100010,
        status: 403,
        message: "促销参数错误!",
      },
    }
  ];
  int32 stars = 2 [
    (protoapi.in) = body,
    (protoapi.desc) = "点赞星数",
    (protoapi.zero) = omit_empty,
    (protoapi.minimum) = {
      val: 1,
      err: {
        code: 100011,
        status: 403,
        message: "点赞星数错误!",
      },
    },
    (protoapi.maximum) = {
      val: 5,
      err: {
        code:100012,
        status: 403,
        message: "点赞星数错误!",
      },
    }
  ];
  int64 publication = 3 [
    (protoapi.name) = "ptime",
    (protoapi.desc) = "出版时间",
    (protoapi.zero) = omit_empty,
    (protoapi.minimum) = {
      val: 946656000, // 不能小于2000-01-01
      err: {
        code: 100013,
        status: 403,
        message: "出版时间错误!"
      }
    },
    (protoapi.maximum) = {
      val: 4102416000, // 不能大于2100-01-01
      err: {
        code: 100014,
        status: 403,
        message: "出版时间错误!"
      }
    }
  ];
  uint32 pages = 4 [
    (protoapi.desc) = "书籍页数"
  ];
  uint64 stock = 5 [
    (protoapi.desc) = "书籍库存数"
  ];
  float price = 6 [
    (protoapi.desc) = "书籍价格",
    (protoapi.zero) = with_empty,
    (protoapi.required) = {
      code: 100016,
      status: 403,
      message: "书籍价格错误",
    },
    (protoapi.minimum) = {
      val: 1,
      err: {
        code: 100017,
        status: 403,
        message: "书籍价格错误",
      }
    }
  ];
  double discount = 7 [
    (protoapi.desc) = "书籍折扣"
  ];
  string name = 8 [
    (protoapi.desc) = "书籍名称",
    (protoapi.required) = {
      code: 100018,
      status: 403,
      message: "书籍名称错误",
    }
  ];
  bytes cover = 9 [
    (protoapi.desc) = "封面数据",
    (protoapi.min_length) = {
      val: 1,
      err: {
        code: 100014,
        status: 403,
        message: "封面数据最小1b",
      }
    },
    (protoapi.max_length) = {
      val: 10240,
      err: {
        code: 100015,
        status: 403,
        message: "封面数据最大10Kb"
      }
    }
  ];
  Genre genre = 10 [
    (protoapi.desc) = "书籍类别(枚举数值)"
  ];
  Genre genre_name = 11 [
    (protoapi.desc) = "书籍类别(枚举名称)"
  ];
  Author author = 12 [
    (protoapi.desc) = "书籍作者信息",
    (protoapi.zero) = conv_empty
  ];
  string isbn = 13 [
    (protoapi.desc) = "书籍惟一编号"
  ];
}

enum Genre {
  UNKNOWN = 0;
  EDUCATION = 1; // 教育
  MAGAZINE = 2; // 杂志
  TEXTBOOK = 3; // 教科书
}

message Author {
  uint64 no = 1 [
    (protoapi.desc) = "作者编号"
  ];
  string name = 2 [
    (protoapi.desc) = "作者名称"
  ];
  string email = 3 [
    (protoapi.desc) = "作者邮箱"
  ];
}

message Void {

}