syntax = "proto3";
package test2;
option go_package = ".;test2";

import "github.com/hezof/protoapi.proto";

enum Enum {
  null = 0[deprecated = true]; one = 1; two = 2;
}

service Demo {

  option (protoapi.http_only) = true;

  option (protoapi.tag) = {
    name: "Demo测试",
    desc: "这是一个Demo测试",
  };

  rpc Simple(Req) returns (Rsp){
    option (protoapi.http) = {
      name: "Simple",
      desc: "简单RPC",
      get: "/demo/simple/:id",
      body: omit,
    };
    option (protoapi.role) = {
      code: 101,
      name: "101",
      desc: "需要101角色",
    };
  }

  rpc Client3(stream Req) returns (Rsp){
    option (protoapi.http) = {
      name: "Client",
      desc: "Streaming Client",
      post: "/demo/client/:id",
      head: "/demo/client/:id",
      body: json,
    };
    option (protoapi.role) = {
      code: 102,
      name: "102",
      desc: "需要102角色",
    };
  }
  rpc Server3(Req) returns (stream Rsp){
    option (protoapi.http) = {
      name: "Server",
      desc: "Streaming Server",
      post: "/demo/server/:id",
      head: "/demo/server/:id",
      body: json,
    };
    option (protoapi.role) = {
      code: 102,
      name: "102",
      desc: "需要102角色",
    };
  }
  rpc Bidirectional(stream Req) returns (stream Rsp){
    option (protoapi.http) = {
      name: "Server",
      desc: "Streaming Server",
      post: "/demo/Bidirectional/:id",
      head: "/demo/Bidirectional/:id",
      body: json,
    };
    option (protoapi.role) = {
      code: 102,
      name: "102",
      desc: "需要102角色",
    };
  }
}


service CopyDemo {

  option (protoapi.http_only) = true;

  option (protoapi.tag) = {
    name: "Demo测试",
    desc: "这是一个Demo测试",
  };

  rpc Simple(Req) returns (Rsp){
    option (protoapi.http) = {
      name: "Simple",
      desc: "简单RPC",
      get: "/copy/simple/:id",
      body: omit,
    };
    option (protoapi.role) = {
      code: 101,
      name: "101",
      desc: "需要101角色",
    };
  }

  rpc Client3(stream Req) returns (Rsp){
    option (protoapi.http) = {
      name: "Client",
      desc: "Streaming Client",
      post: "/copy/client/:id",
      head: "/copy/client/:id",
      body: json,
    };
    option (protoapi.role) = {
      code: 102,
      name: "102",
      desc: "需要102角色",
    };
  }
  rpc Server3(Req) returns (stream Rsp){
    option (protoapi.http) = {
      name: "Server",
      desc: "Streaming Server",
      post: "/copy/server/:id",
      head: "/copy/server/:id",
      body: json,
    };
    option (protoapi.role) = {
      code: 102,
      name: "102",
      desc: "需要102角色",
    };
  }
  rpc Bidirectional(stream Req) returns (stream Rsp){
    option (protoapi.http) = {
      name: "Server",
      desc: "Streaming Server",
      post: "/copy/Bidirectional/:id",
      head: "/copy/Bidirectional/:id",
      body: json,
    };
    option (protoapi.role) = {
      code: 102,
      name: "102",
      desc: "需要102角色",
    };
  }
}

message Req {
  option (protoapi.desc) = "这是一个请求";

  repeated string id = 1 [
    (protoapi.prop) = {
      name: "id",
      desc: "主键字段",
      in: path,
    },
    (protoapi.rule) = {
      required: {
        status: 403,
        code: 1001,
        name: "required",
        message: "必需",
      },
    }];
  optional string name = 2 [
    (protoapi.prop) = {
      name: "name",
      desc: "名称字段",
      in: body,
    },
    (protoapi.rule) = {
      enum: {
        str: ["a", "b", "c"],
        err: {
          status: 403,
          code: 1001,
          name: "required",
          message: "必需",
        }
      }
    }];
  optional uint64 clazz = 3 [
    (protoapi.prop) = {
      name: "class",
      desc: "班级ID",
      in: body,
    },
    (protoapi.rule) = {
      enum: {
        int: [1, 2, 3],
        err: {
          status: 403,
          code: 1001,
          name: "required",
          message: "必需",
        }
      }
    }];
  map<string, int32> scores = 4;
  optional Rsp rsps = 5;
}

enum Sex{
  None = 0;
  Male = 1;
  Female = 2;
}

message Rsp {
  int64 weight = 2 [(protoapi.prop) = {desc: "体重"}];
}